### ISSUE TITLE
Strictness of Either for getCatalog when the Right is not used

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#101]
I am wondering about the effect of the strict Either from [gcatalog](https://github.com/bartavelle/language-puppet/blob/master/Puppet/Daemon.hs#L77)

I also use `puppetresources ` as a lib to do something similar to the `-a` option. Testing a list of nodes, I only care about failures (for continuous integration).

In that case I am wondering if I incur a performance penalty (because either is strict) while doing something like:

```
func node >>= either
  (\err -> putDoc ("Problem with" <+> ttext node <+> ":" <+> getError err </> mempty) >> return Nothing)
  (\x -> return $ Just x)
```
Just a question really, it is quite fast and performance is not currently an issue.

**Comment by bartavelle** [comment]
Given that in that particular case you have to run all the catalog computation to their completion to make sure you succeeded, I would not think so. I am however not very skilled at answering these questions ...

**Comment by PierreR** [comment]
Thanks ;-)
