### ISSUE TITLE
Add stdlib 'ensure_packages' function

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#104]
I will need it because a newest version of puppetlabs docker uses it.

I think the implementation would need to call [create_resources](https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter.hs#L764).

Is this a good idea to do so in the Stdlib module or would it be implement in the Interpreter module ?

**Comment by bartavelle** [comment]
Oh god this is another one of those horrible functions. This will clearly not go into "strict" :) It's ok to do it in the Stdlib file.

The code will look a lot like create_resources, but the list of packages first needs to be filtered ...

**Comment by bartavelle** [comment]
Pushed this into my GHC 7.10 branch (was more convenient to me, even though it makes no sense).

Didn't test it though.

**Comment by bartavelle** [comment]
It's now in master.

**Comment by PierreR** [comment]
It seems to work fine. Thanks.
