### ISSUE TITLE
Add a new option to pass a list of modules for permissive interpretation

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#105]
See #103

**Comment by PierreR** [comment]
I am going to have a go with this issue.

I am trying to : 
 * In strict mode, don't thrown error in `checkStrict` if the current module is in the list of `externalmodules`, just a warning will do.
 * In permissive modue, if the module is in the list of `externalmodules`, decrease the priority of the warning (go for Notice or Info instead).

The only piece of the puzzle I am missing is how to I get the current resource identifier in `CheckStrict` (or in any resolve function) ? I guess from the `InterpreterState` but the doc is rather terse for that matter ;-) ?

**Comment by PierreR** [comment]
Is `Puppet.Interpreter.Types.getScope` the way to go ?

**Comment by PierreR** [comment]
I came up with 
```
isExternalModule :: InterpreterMonad Bool
isExternalModule =
  getScope >>= \case
    ContClass n      -> singleton $ IsExternalModule n
    ContDefine n _ _ -> (singleton . IsExternalModule . head . T.splitOn "::") n
    _                -> return False
```
Does it sound about right ?

`IsExternalModule` is about the same as `IsIgnoredModule`

**Comment by bartavelle** [comment]
That might not work as the class name itself could be of the form `a::b::c`.

**Comment by PierreR** [comment]
Yeah I have normally correct this in the latest master source:
 https://github.com/PierreR/language-puppet/commit/7749a7313f6908eed7cacbb584b21c375b90db62

**Comment by bartavelle** [comment]
Looks ok to me, let's try it !
