### ISSUE TITLE
Add priority to the logger output

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#106]
I would like to add this snippet to the Daemon:

```
      setupLogger = do
      	f <- LOG.setFormatter
      		<$> LOG.streamHandler stdout LOG.WARNING
      		<*> pure (LOG.simpleLogFormatter "$prio: $msg")
      	LOG.updateGlobalLogger loggerName $ LOG.setHandlers [f]
```
It works nicely and I have found the output to be clearer.

Still it is a bit odd that I do it just for 'WARNING'. Do you know a better way to do this ? Do I really need to create one `f` for each priority ?

Another option is to append `p` when we `mapM_` but  this is a bit at odd with how a logger is supposed to be used.

**Comment by PierreR** [comment]
The best I can come up with is:
```
      stdoutHandler p = setFormatter
                        <$> streamHandler stdout p
                        <*> pure (simpleLogFormatter "$prio: $msg")
      setupLogger = do
         hs <- for [LOG.WARNING, LOG.ERROR] stdoutHandler
         LOG.updateGlobalLogger loggerName $ LOG.setHandlers hs
```
It seems good enough for me.

Are you OK if I push this ?

**Comment by PierreR** [comment]
Let me know if the fix is OK or not.

Cheers

**Comment by bartavelle** [comment]
Seems OK to me !
