### ISSUE TITLE
Add user/group test back to OptionalTests

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#107]
I have added back the user/group tests. The list of known groups and users is still hard coded but the idea is to allow the user to provide this list (later PR).

PR is coming

**Comment by PierreR** [comment]
This PR introduce the pragma "{-# LANGUAGE AutoDeriveTypeable #-}" which might or might not ok as it was introduced recently (let me know)

Could you review these changes ? I will add some notes in there. There is something particularly that drove me half crazy and I will try to explain it ... If you can't offer an explanation I will try stackoverflow or reddit ...

**Comment by bartavelle** [comment]
I don't know what `throwM` does in IO when you throw something that's not an exception. Perhaps that's the cause ?

One of the reason I wanted to integrate the tests with some test framework was to have that kind of problems solved for me (also pretty printing of test results).

**Comment by PierreR** [comment]
`PrettyError` is now an exception:

https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter/Types.hs#L170

**Comment by PierreR** [comment]
I have found the answer : 
http://stackoverflow.com/questions/29334118/wicked-exceptions-behavior-using-the-exceptions-package

I guess this is what one would call "une erreur de débutant" ;-)

**Comment by bartavelle** [comment]
Oh right, I made that one too once :)

**Comment by PierreR** [comment]
I am leaving this open because I still need to let the user gives its own list of known user & groups.

My take would be to lookup for a yaml file in the `tests` directory with a specific name such as `knownusersgroups.yaml` and to override the list if such a file exists.

Is this ok by you ?

**Comment by bartavelle** [comment]
Yup !

**Comment by PierreR** [comment]
Thinking about it a bit more, it is actually a good opportunity to introduce an `options.yaml` file where users could override some `Preferences` such as `knownusers`, `knowngroups`, `ignoremodules` ...

**Comment by bartavelle** [comment]
That would be great !

**Comment by PierreR** [comment]
PS: I am only reading the 2 params `knownusers` & `knowngroups` for now but I think it is extensible enough to read others in the future.

I had to patch `Erb/Compute.hs` and the lower bound on `lens` on the master to fix compilation issues.

**Comment by bartavelle** [comment]
Awesome, I'll restore the lens bound once it is released.
