### ISSUE TITLE
Clean up the PuppetDB API

### ISSUE THREAD

**Issue by bartavelle** [bartavelle/language-puppet#108]
I will soon write a full puppetmaster replacement. I want to use [servant](http://hackage.haskell.org/package/servant) for that.

To cut down on dependencies, I plan to migrate the current PuppetDB backend to servant. It does now live in the servant branch.

It would be nice if someone with access to a real puppetDB could check if there are regressions when connecting to a PuppetDB ...

**Comment by PierreR** [comment]
I have access to a real puppetDB so I will be able to help (but not before the end of next week).

**Comment by bartavelle** [comment]
So I have moved it to a GHC 7.10 branch, as the servant move drops the requirement for the `iconv` package that doesn't build for 7.10.

I think I fixed the build for 7.10, and tried to reduce the warnings as much as I could (that's why there are extra `import Prelude` lines now).

I also removed all references to `Control.Monad.Error`, which is deprecated.

**Comment by bartavelle** [comment]
I'll test that it still works as expected with GHC 7.8 tomorrow.

**Comment by bartavelle** [comment]
This seems OK, so I merged all my changes with master. I'll test it properly in the next days.
