### ISSUE TITLE
noop attributes is ignored

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#109]
I don't really see why this parameter should be ignored:

https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter.hs#L675

Shall I remove the line ?

**Comment by bartavelle** [comment]
It's just that it should be supported, and didn't bother to do so.

**Comment by PierreR** [comment]
When I remove the line, it just works as I would expect at least as a client. I am not sure it is ok to remove it though ...

**Comment by bartavelle** [comment]
I think this can safely be removed.

**Comment by PierreR** [comment]
Done in 3b2eb6ce79aa11aed661c7619bfef87a052c1162
