### ISSUE TITLE
language-puppet-1.1.1 can't compile its test suite

### ISSUE THREAD

**Issue by peti** [bartavelle/language-puppet#111]
We get the following errors in NixOS trying to build with GHC 7.10.1:

    Preprocessing test suite 'test-puppetdb' for language-puppet-1.1.1...
    [1 of 1] Compiling Main             ( tests/puppetdb.hs, dist/build/test-puppetdb/test-puppetdb-tmp/Main.dyn_o )

    tests/puppetdb.hs:31:5:
        Couldn't match type ‘either-4.3.3.2:Control.Monad.Trans.Either.EitherT
                               PrettyError IO’
                       with ‘IO’
        Expected type: IO ()
          Actual type: either-4.3.3.2:Control.Monad.Trans.Either.EitherT
                         PrettyError IO ()
        In the first argument of ‘(>>=)’, namely
          ‘replaceFacts pdb [(ndname, nfacts)]’
        In a stmt of a 'do' block:
          replaceFacts pdb [(ndname, nfacts)] >>= checkError "replaceFacts"

    tests/puppetdb.hs:31:45:
        Couldn't match type ‘()’ with ‘S.Either x0 a0’
        Expected type: () -> IO a0
          Actual type: S.Either x0 a0 -> IO a0
        In the second argument of ‘(>>=)’, namely
          ‘checkError "replaceFacts"’
        In a stmt of a 'do' block:
          replaceFacts pdb [(ndname, nfacts)] >>= checkError "replaceFacts"

    tests/puppetdb.hs:32:5:
        Couldn't match type ‘either-4.3.3.2:Control.Monad.Trans.Either.EitherT
                               PrettyError IO’
                       with ‘IO’
        Expected type: IO ()
          Actual type: either-4.3.3.2:Control.Monad.Trans.Either.EitherT
                         PrettyError IO ()
        In the first argument of ‘(>>=)’, namely ‘commitDB pdb’
        In a stmt of a 'do' block: commitDB pdb >>= checkError "commitDB"

    tests/puppetdb.hs:32:22:
        Couldn't match type ‘()’ with ‘S.Either x1 a1’
        Expected type: () -> IO a1
          Actual type: S.Either x1 a1 -> IO a1
        In the second argument of ‘(>>=)’, namely ‘checkError "commitDB"’
        In a stmt of a 'do' block: commitDB pdb >>= checkError "commitDB"

    tests/puppetdb.hs:40:5:
        Couldn't match type ‘either-4.3.3.2:Control.Monad.Trans.Either.EitherT
                               PrettyError IO’
                       with ‘IO’
        Expected type: IO ()
          Actual type: either-4.3.3.2:Control.Monad.Trans.Either.EitherT
                         PrettyError IO ()
        In the first argument of ‘(>>=)’, namely
          ‘replaceCatalog fpdb (generateWireCatalog ndname mempty mempty)’
        In a stmt of a 'do' block:
          replaceCatalog fpdb (generateWireCatalog ndname mempty mempty)
          >>= checkError "replaceCatalog"

    tests/puppetdb.hs:40:72:
        Couldn't match type ‘()’ with ‘S.Either x2 a2’
        Expected type: () -> IO a2
          Actual type: S.Either x2 a2 -> IO a2
        In the second argument of ‘(>>=)’, namely
          ‘checkError "replaceCatalog"’
        In a stmt of a 'do' block:
          replaceCatalog fpdb (generateWireCatalog ndname mempty mempty)
          >>= checkError "replaceCatalog"

    tests/puppetdb.hs:41:5:
        Couldn't match type ‘either-4.3.3.2:Control.Monad.Trans.Either.EitherT
                               PrettyError IO’
                       with ‘IO’
        Expected type: IO ()
          Actual type: either-4.3.3.2:Control.Monad.Trans.Either.EitherT
                         PrettyError IO ()
        In the first argument of ‘(>>=)’, namely ‘commitDB fpdb’
        In a stmt of a 'do' block: commitDB fpdb >>= checkError "commit 2"

    tests/puppetdb.hs:41:23:
        Couldn't match type ‘()’ with ‘S.Either x3 a3’
        Expected type: () -> IO a3
          Actual type: S.Either x3 a3 -> IO a3
        In the second argument of ‘(>>=)’, namely ‘checkError "commit 2"’
        In a stmt of a 'do' block: commitDB fpdb >>= checkError "commit 2"

**Comment by bartavelle** [comment]
I fixed the tests in 1.1.1.2
