### ISSUE TITLE
Interpret global `settings::xxx` variables

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#112]
I have an error with the puppetlabs puppetdb package because of some global variables such as  [`$settings::confdir`](https://github.com/puppetlabs/puppetlabs-puppetdb/blob/master/manifests/params.pp#L75)

Would it be easy to include these (ugly) global variables within the interpreter ?

**Comment by bartavelle** [comment]
It would be nice to have a list of those and their meaning first. Do you know where we can get it ?

**Comment by PierreR** [comment]
This is the puppet doc:
https://docs.puppetlabs.com/puppet/latest/reference/lang_facts_and_builtin_vars.html#puppet-master-variables

I would propose to start with a basic set of known master variables (and complete if needed) ...

**Comment by bartavelle** [comment]
Injecting them along with the facts should work. An alternative would be to use the `Preferences` structure to populate this list. I'll try to take a look during the week.

**Comment by bartavelle** [comment]
Just pushed some initial implementation. See : https://github.com/bartavelle/language-puppet/blob/0372b8306c8aa88fb833c7f095415fa66e240668/Puppet/Preferences.hs#L131-L133

You will need to add the keys you are interested in. It might be nice to add this to the defaults YAML file too.

**Comment by PierreR** [comment]
I have added it to the default YAML here (I actually need settings::confdir to be /etc/puppet otherwise I get the error `Path must be absolute, not ./routes.yaml for parameter path`.

https://github.com/PierreR/language-puppet/commit/0621dbf6c818f0939e8115259094679c70992f84

If it is OK by you I will push to your repo

**Comment by bartavelle** [comment]
Looks good to me !
