### ISSUE TITLE
defined function not enabled in strict mode

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#114]
I am reading some facts that are setup before the configuration phase on the node (machine) but one of them is optional.  I simulate this using the `--pdbfile` flag

So in `site.pp` I need to check for the existence of `$::subgroup`. The use of the `defined` puppet function seems totally legitimate in this case.

Is there another better way to handle such a case. I don't want to disable the strict mode just for this.

Could we go for an `info` anytime `defined` is used instead of a warning in permissive mode and a 'noway' in strict mode ?

https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter/Resolve.hs#L396

**Comment by PierreR** [comment]
Ok I believe I have found a better way.

I just explicit add `subgroup` using `----facts-override` and then I use `if $::subgroup != undef` instead.

**Comment by PierreR** [comment]
Oh well it does not work ... because `--facts-override` takes precedence over the `--pdbfile`.

 `--facts-default` is not really an option for me because I need to override for other items in that file.

**Comment by PierreR** [comment]
I actually don't understand why we can't have both `--facts-default` and `facts-override` together ?

**Comment by bartavelle** [comment]
It's just because it's not implemented ... no reason really.

The problem with defined is that it can either check if a resource or a variable has been defined. Given that variables are already parse dependent, this could indeed be acceptable. For resources I think it is evil.

**Comment by PierreR** [comment]
I might go and implement it.

What about dropping the command line option for both `- -facts-default` and `facts-override` and use the `defaults.yaml` instead ? 

Thanks for the explanation about `define`.

**Comment by bartavelle** [comment]
Yes, let's just trop the command line. I don't think it's terribly practical.
