### ISSUE TITLE
Releasing 1.1.1.3

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#116]
Could you make a new release ?

The update to servant-4.0 will probably fix the nix build:

http://hydra.cryp.to/build/910955/nixlog/1

Thanks,

Cheers

**Comment by bartavelle** [comment]
Done ... but I just realized I made a typo and release 1.1.3 ...

**Comment by bartavelle** [comment]
IDK how to tell the build server to evaluate the next version ...

**Comment by PierreR** [comment]
It is automatic ... Every now and then (usually a couple of days) hydra would rebuild all hackage with the latest version set. 

When a package fails for too long it is removed from the set (and pushed back when it is fixed). That's what happened with servant 4.0.0, the build has been "fixed for nix" in 4.1.

What `hydra` gives you is the assurance that `language-puppet` builds with the dependencies when set to the latest versions. It might be completely legitimate for a package to fail for a while because you cannot expect all packages to fulfill this requirement at all time.

I have just pushed some upperbound changes so that `cabal configure` works in nixos. I don't think it impacts the future `language-puppet-1.1.3" build on hydra but let's wait and see.

Thanks for the new build.

**Comment by PierreR** [comment]
Well I broke the tests ... (see http://hydra.cryp.to/build/913571/nixlog/1).

Sorry about that. I have just pushed the fix.

Could you release  1.1.3.1 ?

**Comment by bartavelle** [comment]
Will try tonight

**Comment by bartavelle** [comment]
Will try tonight

**Comment by bartavelle** [comment]
done

**Comment by PierreR** [comment]
Cool. It is green.  http://hydra.cryp.to/build/919605
Thanks
