### ISSUE TITLE
Lua table are translated as Array ?

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#117]
I had a go trying some lua. I need to return a Puppet hash:

https://github.com/puppetlabs/puppetlabs-postgresql/blob/master/lib/puppet/parser/functions/postgresql_acls_to_resources_hash.rb

But a simple try like this:

```
function postgresql_acls_to_resources_hash (acls, id)
  return {type = 'bar', database = 'all', user = 'all', auth_method = 'trust'}
end
```

seems to end up as an array : 

```
ERROR: (postgres_testing) Don't know how to convert this to a string:
[all
,bar
,trust
,all] 
```

Anyhow I don't really like writing this in lua ...Mainly it is going to be harder for shipping it (I don't believe puppetlabs modules are going to accept lua files). Could we have a namespace for common puppetlabs module and provide a haskell implementation instead (along the side of `stdlib`).

**Comment by bartavelle** [comment]
In Lua everything is a table. I can take a look at the current code to see if I can add a heuristic that would detect dictionaries.

The best course would be to be able to evaluate the ruby functions directly, but that requires writing a *lot* of plumbing.

**Comment by bartavelle** [comment]
I modified the code a bit so that hashes are properly retrieved. Now arrays won't work ;)

**Comment by PierreR** [comment]
Would the latest version help ?

https://github.com/osa1/hslua/commit/558ba63d54c3c6c15ed958018365bdde7bb92987

**Comment by bartavelle** [comment]
I upgraded to the latest version, and for some reason this code doesn't seem to work :/

**Comment by PierreR** [comment]
I have ended up doing it in Haskell : 
https://github.com/PierreR/language-puppet/commit/d50eda0f0cc834c45165382fa6851c5dc181f269

Is that alright ? Shall I push it ?

The Lua plugin system might be a lot of pain for little benefits ? (Are you using it yourself ?)

**Comment by bartavelle** [comment]
Seems ok to me ! It would be nice to be able to activate the functions conditionally (for example if a ruby function with the same name is loaded)

**Comment by PierreR** [comment]
>  It would be nice to be able to activate the functions conditionally

Is this to minimize memory space or naming collision ?

**Comment by bartavelle** [comment]
For collision, I don't think this would affect memory usage.
