### ISSUE TITLE
Erb error with dirname(file)

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#121]
I have got an error in erb templates starting with:
```
<%= ERB.new(File.read(File.expand_path("_header.erb",File.dirname(file)))).result(binding) -%>
```
```
ERROR: (puppet/foreman_testing) no implicit conversion of Float into String
(erb):1:in `dirname'
(erb):1:in `get_binding'
/usr/lib/ruby/2.2.0/erb.rb:863:in `eval'
/usr/lib/ruby/2.2.0/erb.rb:863:in `result'
/home/vagrant/projects/cicd/language-puppet/.cabal-sandbox/share/x86_64-linux-ghc-7.10.1/language-puppet-1.1.3.1/ruby/hrubyerb.rb:107:in `runFromContent'
/home/vagrant/projects/cicd/language-puppet/.cabal-sandbox/share/x86_64-linux-ghc-7.10.1/language-puppet-1.1.3.1/ruby/hrubyerb.rb:102:in `runFromFile'
```

https://github.com/theforeman/puppet-foreman/blob/master/templates/database.yml.erb#L1

Do you have any idea how I could alleviate the problem ? I don't care if the solution would just ignore this kind of  input line from template file ...

**Comment by bartavelle** [comment]
What's the value of `file` ?

**Comment by PierreR** [comment]
Well I don't know (same for binding)... I thought it was some function that Erb recognizes ...
I am just trying to use this foreman puppetlabs module (without ignoring it totally) ...

**Comment by bartavelle** [comment]
I know what bindings is, but not sure about file ... if it's something built in it might be the path ?

**Comment by PierreR** [comment]
So I have tested it and ´file´ is the absolute path of the template.

**Comment by bartavelle** [comment]
Just pushed something, does it help ?

**Comment by PierreR** [comment]
It works fine. Thanks !
