### ISSUE TITLE
puppetresources won't parse `::apache::mod {`

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#123]
`puppetresource` fails to parse this line :

```
 ::apache::mod { 'passenger':

puppetresources --parse modules/apache/manifests/mod/passenger.pp
puppetresources: parse error:"modules/apache/manifests/mod/passenger.pp" (line 46, column 30):
unexpected ":"
expecting Statement

```
from [puppetlabs-apache](https://github.com/puppetlabs/puppetlabs-apache/blob/master/manifests/mod/passenger.pp#L46)

If I remove the semi-colons, the parse succeeds:
```
apache::mod { 'passenger':
```

**Comment by bartavelle** [comment]
It actually parses it concatenated to the previous line :/

**Comment by bartavelle** [comment]
class apache::mod::passenger {
        $_path = $mod_path
        ::apache::mod 
    }

Parses as :

    $_path = $mod_path::apache::mod

**Comment by bartavelle** [comment]
This will be horrible to fix !

**Comment by PierreR** [comment]
As a note, if you add a BR it still fails:
```
class apache::mod::passenger {
    $_path = $mod_path
    
    ::apache::mod 
}
```

**Comment by bartavelle** [comment]
I just pushed something, it might have random effects (although I am not too worried).

**Comment by PierreR** [comment]
I have just pulled the change but it does not seem to make any difference :-(

**Comment by PierreR** [comment]
I have just been bitten by a related problem ... Here the nginx module goes into "fully qualify classes, defines and variables":

https://github.com/jfryman/puppet-nginx/commit/f18dcf0f1f9daad3ab13d8aa8668589b6f6732ab#diff-a43305b17067171ae7b2f2ebefd53622L481

All goes fine except for a problem that was really difficult to track down. This specific change makes is the culprit (https://github.com/jfryman/puppet-nginx/blob/f18dcf0f1f9daad3ab13d8aa8668589b6f6732ab/manifests/resource/vhost.pp#L481):
```
   if $use_default_location == true {
     # Create the default location reference for the vHost
-    nginx::resource::location {"${name_sanitized}-default":
+    ::nginx::resource::location {"${name_sanitized}-default":
```
Because of this change, I have got the following error:
```
ERROR: (sonarqube_prod) Unknown resource Nginx::Resource::Location[svappcavl596.prd.srv.cirb.lan-default] used in the following relationships: Nginx::Resource::Location[svappcavl596.prd.srv.cirb.lan-default] -> Concat::Fragment[0f70f2e8dba86039d81d9050d6c7e511] # "./modules/nginx/manifests/resource/location.pp" (line 350, column 24) at # "./modules/nginx/manifests/resource/location.pp" (line 379, column 3)
```
The concat implicit requirement is not fulfilled anymore ...

**Comment by bartavelle** [comment]
I have some idea on how to fix this but I am away for a few weeks...

**Comment by PierreR** [comment]
No problem ;-)

**Comment by PierreR** [comment]
Extra note: the related PR for the nginx puppet module has been merged so it seems OK to agree that it is not such a good idea to qualify defined resource type.

**Comment by bartavelle** [comment]
Didn't mean to autoclose this, it seems to work for me.

**Comment by PierreR** [comment]
It has been working for me too. Thanks
