### ISSUE TITLE
`Defined` for resource instance using Anchor

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#124]
Given [this code] (https://github.com/jfryman/puppet-nginx/blob/e710cccd4c9835819849e2e0509bb6bf93f7a165/manifests/init.pp#L222)  and the following declaration:

```  
Anchor['nginx::begin']
 ->
class { 'nginx::config' :
    confd_purge  => true,
    vhost_purge  => true,
}

class { 'nginx' :
    manage_repo   => false,
}
```

defined(Class['::nginx::config'])  return `false` while it should be `true`.

See [this issue](https://github.com/jfryman/puppet-nginx/issues/536)

I guess this might be horrible to fix ...

**Comment by bartavelle** [comment]
What does it do when you replace with `defined(Class['nginx::config'])` (without the `::` header) ?

**Comment by bartavelle** [comment]
It tried it and got:

```
ERROR: (a.b) Override of parameters of the following resource is forbidden in the current context:
class {
  nginx::params: # "/tmp/x/manifests/site.pp" (line 4, column 11) a.b [Scope []]
    ;
} # "/tmp/x/modules/nginx/manifests/config.pp" (line 202, column 5) at # "/tmp/x/modules/nginx/manifests/config.pp" (line 287, column 10)
```

**Comment by bartavelle** [comment]
Isn't it better now ? Class reference names are now normalized.

**Comment by PierreR** [comment]
I am going to try later today.

I was planning to describe in more detail the problem I have with global scoping but I haven't found the time yet. Yesterday for instance I was writing something such as `require => Class['profile::mycompany']` where profile is an external module. In that case `require => Class['profile::mycompany']` was working but  `require => Class['::profile::mycompany']` was not. I would have expected the completely opposite behavior.

**Comment by bartavelle** [comment]
Hopefully both cases should work now !

**Comment by PierreR** [comment]
Work nicely so far. I am closing the issue. Thanks
