### ISSUE TITLE
Hiera lookup won't override params in a Class created 	conditionally

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#125]
Suppose the following test class:
```
class test {
  $foo = 1
  $bar = hiera('nginx::config::worker_processes')
  notify {"lookup ${bar}":}
  if !defined(Class['::nginx::config']) {
    class { '::nginx::config':
      worker_processes => $foo,
    }
  }
}

```
in hiera we define: 
```
nginx::config::worker_processes: 2
```

The output shows that the notification is correct:
```
notify {
  lookup 2: # "./modules/test.pp" (line 4, column 11) sonarqube_testing [Scope [class application::role::sonarqube]]
    withpath => false,
    require  => Class[test];
}
```
but we will have
```
  /etc/nginx/nginx.conf: # "./modules/nginx/manifests/config.pp" (line 263, column 10) 
  content => user nginx;\nworker_processes 1;\....
```
Checking on a live puppet instance, it does get `worker_processes 2`.

This is probably related to #124

This problem is revealed in `jfryman/nginx` puppet module:
See
* https://github.com/jfryman/puppet-nginx/issues/536
* https://github.com/jfryman/puppet-nginx/issues/655

**Comment by bartavelle** [comment]
Wait what ? Shouldn't explicit argument override everything ?

**Comment by PierreR** [comment]
Well the nginx use case is a bit different. `$foo` is actually undef (but it defaults to 1 inside `::nginx::config` )
```
class test {
  $foo = undef
  $bar = hiera('nginx::config::worker_processes')
  notify {"lookup ${bar}":}
  if !defined(Class['::nginx::config']) {
    class { '::nginx::config':
      worker_processes => $foo,
    }
  }

``` 
In that case, puppet will correctly set `worker_processes` to `2` but puppetresources will believe it is `1`. Actually with d108c061feebd it might now believe it is `undef` ?

Here is the nginx source:
https://github.com/jfryman/puppet-nginx/blob/master/manifests/init.pp

**Comment by bartavelle** [comment]
Oh I see ! I wondered why that case was set that way before I changed it ... it should really document more.

**Comment by bartavelle** [comment]
What about now ?

**Comment by PierreR** [comment]
I don't get the error anymore but `worker_processes` is still `1` instead of `2`. This was the situation before d108c06 but it is misleading because puppet will set it to `2`.

**Comment by bartavelle** [comment]
I refactored the problematic function so that it is clearer. I might have failed :) (see 98a79e1)

It must be tested as it is likely I broke something again ...

**Comment by PierreR** [comment]
With 98a79e14 I have got the following error:
```
Could not resolve variable $servername in context puppet::server or root at # ./modules/puppet/manifests/server.pp:4:1
```
where the incriminated line is
```
class puppet::server (
  $version,
  $pkg = $pkg,
  $puppet_has_report = true,
  $servername          = $::fqdn,
  $certname            = $servername,
  $autosign            = []
){
....
```
$fqdn is a fact defined in my tests/defaults.yaml as `factsdefault`: 
```
factsdefault:
  subgroup:
  http_proxy:
  https_proxy:
  jenkins_plugins: "dummy"
  docker::version: "1.2.0"
  fqdn: utesting
  selinux: false
  maven_version: '3.2.5'
  rubyversion: '1.8.7'
```

**Comment by PierreR** [comment]
I have just realized it has nothing to do with `$::fqdn`. The problem is the re-use of the $severname variable:
So this is OK:
```
class puppet::server (
  $servername,
){
  $certname            = $servername
```
But this is KO:
```
class puppet::server (
  $servername,
  $certname            = $servername,
){
```

**Comment by PierreR** [comment]
Apart from this little problem, 98a79e1 does fix the issue  ;-)

**Comment by bartavelle** [comment]
Variables are now loaded one after the other instead of in bulk at the end of the argument declaration.

**Comment by PierreR** [comment]
It works fine. Thanks.
