### ISSUE TITLE
Are ext_funcs looked up in Erb templates ?

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#127]
In Puppet, functions defined in `modulename/lib/puppet/parser/functions/` can be used inside `erb` templates by prefixing them by `function_`.

To support the [`apache` puppetlabs module](https://github.com/puppetlabs/puppetlabs-apache/blob/master/templates/httpd.conf.erb#L3), I add `bool2httpd` into our haskell module `Puppetlabs`.

It still does not work and I am now under the impression that `prefExtfuncs` (including the one defined in lua files) won't be lookup in `erb` templates. Is this correct ?

If so, would it be hard to support this ?

**Comment by bartavelle** [comment]
This is correct, and I think this *could* be possible. I'll think about it.

**Comment by bartavelle** [comment]
Just pushed something ... does it help ?

**Comment by bartavelle** [comment]
It will return bogus answer for some functions though (like `defined`) because we don't have access to the puppet state from withing the templates.

**Comment by PierreR** [comment]
It does not work. It actually does not go into `def method_missing(sname,*args,&block)` when the error occurs. I add a `puts` statement there and nothing gets printed.

In case it helps here is the error:
```
ERROR: (puppet/foreman_testing) undefined method `function_bool2httpd' for #<Scope:0x007fd7a800bd38>
(erb):3:in `get_binding'
/usr/lib/ruby/2.2.0/erb.rb:863:in `eval'
/usr/lib/ruby/2.2.0/erb.rb:863:in `result'
```

**Comment by bartavelle** [comment]
Can you tell me how to reproduce your setup ? I suppose I need the apache module and your implementation of bool2httpd ?

**Comment by PierreR** [comment]
I have just committed the implementation of the function.

I was wondering if the following change is not required too ? (it does not fix the problem though)

```
--- a/Puppet/Daemon.hs
+++ b/Puppet/Daemon.hs
@@ -77,12 +77,12 @@ initDaemon prefs = do
     pfilecache    <- newFileCache
     let getStatements = parseFunction prefs pfilecache parserStats
     intr          <- startRubyInterpreter
-    getTemplate   <- initTemplateDaemon intr prefs templateStats
     hquery        <- case prefs ^. hieraPath of
                          Just p  -> either error id <$> startHiera p
                          Nothing -> return dummyHiera
     luacontainer <- initLuaMaster (T.pack (prefs ^. puppetPaths.modulesPath))
     let myprefs = prefs & prefExtFuncs %~ HM.union luacontainer
+    getTemplate   <- initTemplateDaemon intr myprefs templateStats
     return (DaemonMethods (gCatalog myprefs getStatements getTemplate catalogStats hquery) parserStats catalogStats templateStats)
```

**Comment by bartavelle** [comment]
Oh perhaps it is !

**Comment by bartavelle** [comment]
I tried something significantly more complicated here. I hope this doesn't break anything ...

**Comment by PierreR** [comment]
I am going further with it trying to test the new code as much as I can.

So far so good except that I have probably discovered an other little "bug":

`puppetresources` cannot resolve `1 == -1` or anything with a minus such as `x == -y`

Here is the code and the error:
https://github.com/puppetlabs/puppetlabs-apache/blob/master/manifests/default_mods.pp#L16
```
ERROR: (puppet/foreman_testing) Don't know how to resolve this expression:
- (1) at # "./modules/apache/manifests/default_mods.pp" (line 16, column 9)
```

**Comment by bartavelle** [comment]
For all these years, this case was not handled ... this should be the case now.

**Comment by PierreR** [comment]
Thanks for the quick fix.

There is also a kind of a "debug" statement left. I am not sure if it is on purpose.
```
> puppetresources -p . -o pgserver_testing --hiera ./tests/hiera.yaml --pdbfile ./tests/facts.yaml -n postgresql94
("versioncmp",[PString "9.4",PString "9.1"],Right (PString "1"))
package {
  postgresql94: # "./modules/postgresql/manifests/client.pp" ( .....
```

**Comment by bartavelle** [comment]
woops ...

**Comment by bartavelle** [comment]
Fixed.

**Comment by PierreR** [comment]
Looks good. Thanks for the fix !
