### ISSUE TITLE
The file function won't find correct path.

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#128]
AFAIK the `template` and `file` function would find files using the same scheme:

So `application/salt/db.sql` will load the file `<MODULES DIRECTORY>/application/files/salt/db.sql`.

While this works with the `template` function, it does not with the `file` function.

I have tested it changing the call from `file(` to `template(` after getting an error about `No file found in [application/salt/db.sql]` and indeed a dummy file would then be found in `<MODULES DIRECTORY>/application/templates/salt/db.sql`.

**Comment by bartavelle** [comment]
I didn't it could work like that with relative path !

**Comment by bartavelle** [comment]
What about now ?

**Comment by PierreR** [comment]
It works nicely. Thanks !
