### ISSUE TITLE
Support for and/or in collectors

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#132]
It looks like `puppetresources` does not support `and/or` in resource collector:
```
Package <| tag == 'orderedinstall' and ensure == 'absent' |> -> Package <| tag == 'orderedinstall' and ensure != 'absent' |>
```
will fail with `error on this: unexpected "a"`

Here is the relevant doc:
https://docs.puppetlabs.com/puppet/latest/reference/lang_collectors.html#and

Cheers

**Comment by bartavelle** [comment]
Well, it *should* be supported. I'll check.

**Comment by bartavelle** [comment]
Should work properly now

**Comment by PierreR** [comment]
While this works:
```
runPParser puppetParser "test" " Package <| name == 'git' and ensure == 'absent' |> -> User ['jenkins'] |>"

Right (fromList [ResourceCollection (RColl Collector "package" (AndSearch (EqualitySearch "name" (Terminal (UString "git"))) (EqualitySearch "ensure" (Terminal (UString "absent")))) (fromList []) ("test" (line 1, column 2) :!: "test" (line 1, column 53)))])
```

But within a file `Package <| name == 'git' and ensure == 'absent' |> -> User ['jenkins']` will still throw an exception:

```
> puppetresources --parse ./modules/profile/manifests/jenkins/slave.pp                                 
puppetresources: parse error:"./modules/profile/manifests/jenkins/slave.pp" (line 18, column 28):
unexpected "a"
expecting Statement
```

```

**Comment by bartavelle** [comment]
I suppose I will have to write a real expression parser here  ...

**Comment by bartavelle** [comment]
(Also note that you should add `<* eof` or something like that when using `runPParser` or you might get just a partial evaluation)

**Comment by bartavelle** [comment]
(and indeed, the part after the arrow isn't parsed !)

**Comment by bartavelle** [comment]
There is a serious bug here, it is parsed but seems discarded.

**Comment by bartavelle** [comment]
Can I have the offending file ? Or a minimal sample ?

**Comment by PierreR** [comment]
```
#
# Typical specific slave requirement
#
class profile::jenkins::slave (
){
  realize (
    Group['jenkins'],
    User['jenkins'],
    Package['git'],
  )
  Package <| name == 'git' and ensure == 'absent' |> -> User ['jenkins']
  }
}
```
Here is a minimal sample. It is not realistic because I am not the owner of the offending file. So this was my attempt to reproduce the bug that has been reported to me.

Let's me know if you need more info.
}

**Comment by bartavelle** [comment]
I modified the example to remove the last `}`, and it parses properly with a fully fledged expression parser. Pushing in a minute.

**Comment by bartavelle** [comment]
See e44ce42

**Comment by PierreR** [comment]
It works fine !

Thanks.
