### ISSUE TITLE
Implement appending-to-resource-attributes

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#134]
While I am messing up with resource collector I am wondering if you would support [appending to resource attributes](https://docs.puppetlabs.com/puppet/latest/reference/lang_classes.html#appending-to-resource-attributes
) (using the `+>`)

My motivation is to replace this snippet

```
  exec {'jenkins docker membership':
    unless  => 'grep -q \'dockerroot\\S*jenkins\' /etc/group',
    command => 'usermod -aG dockerroot jenkins',
    require => [Class['profile::docker'], User['jenkins']],
  }

```
with this one:

```
  User <| title == jenkins |> { groups +> "dockerroot" }
```

Or maybe there is a better idea for such a use case ?

**Comment by bartavelle** [comment]
That could be possible yes.

**Comment by PierreR** [comment]
In `User <| title == 'jenkins' |> { groups => 'dockerroot' }`, ` { groups => 'dockerroot' }` parses as a `V.Vector (Pair T.Text Expression)`

When introducing  `groups +> 'dockerroot'` what would be  the new parsed type ?

**Comment by bartavelle** [comment]
Perhaps something like `V.Vector DefaultSomething` ?

    data DefaultSomething = DefaultValue Text Expression
                          | DefaultAppend Text Expression

**Comment by bartavelle** [comment]
Or

    data DefaultSomething = DefaultSomething Something Text Expression

    data Something = Append | DefaultValue

**Comment by PierreR** [comment]
What about
```
data AttributeDecl = AttributeDecl Text ArrowOp Expression
data ArrowOp = AppendArrow | AssignArrow
```
Do you have a better name scheme for describing `=>` or `+>` (I don't know how a rubyist would call them)

**Comment by bartavelle** [comment]
Looks excellent to me.

**Comment by bartavelle** [comment]
And no, I am not very good at naming things ...

**Comment by PierreR** [comment]
I think there is a bug [here](
https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter.hs#L332-L336). I think `curmap` is always empty. Can you confirm ?

**Comment by PierreR** [comment]
Î have been adding two specs for this. Could you check them out ?

Should [this case](https://github.com/bartavelle/language-puppet/blob/master/tests/InterpreterSpec.hs#L42) throw an exception ? Right now it does nothing (keeping the initial groups attribute intact).

**Comment by bartavelle** [comment]
Those specs are nice! I don't really know what puppet does in that case ...

**Comment by PierreR** [comment]
I have tested the case with puppet. What's happening is that a user is created with the groups as declared in the collector. I will add a new issue about this and modify the spec accordingly.

Here is the pp file I use:
```
class test {
  group {'test1':
    ensure => present,
  }
  group {'test2':
    ensure => present,
  }
  user {'test':
    ensure => present,
    groups => 'test1'
  }

  User <| title == 'test' |> { groups => "test2" }
}
```
And it generated a user 'test' with groups test,test2 using puppet 3.7.2

**Comment by bartavelle** [comment]
I just pushed a tentative fix, can you check if it behaves as you wish ?
