### ISSUE TITLE
Implement contain function

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#135]
https://docs.puppetlabs.com/puppet/latest/reference/lang_containment.html#the-contain-function

Some puppetlabs modules has started using it (it requires puppet >=3.4)

**Comment by bartavelle** [comment]
So it should do something now, but I am unsure of the semantics of this versus include. I don't understand why the dependency with the class isn't transitive ...

**Comment by PierreR** [comment]
`containment` is a tricky topic in puppet:
https://docs.puppetlabs.com/puppet/latest/reference/lang_containment.html

My understanding is that when you require a resource, it only requires toplevel declaration (not the included resources). The `contains` function is a way to change this behavior. Whenever the class is required, all contain resources will be required as well.

**Comment by PierreR** [comment]
So the `contain` function is a way to achieve [the anchor pattern] (https://blog.mayflower.de/4573-The-Puppet-Anchor-Pattern-in-Practice.html) with a clearer syntax.

**Comment by bartavelle** [comment]
I think the way I implemented `language-puppet` is that `include` is basically `contain` ... this might require a look over ...

**Comment by PierreR** [comment]
The fix causes a problem at https://github.com/garethr/garethr-docker/blob/master/manifests/init.pp#L226-L233

Here is the error:

```
Class  docker::install  was already included using the 'include' keyword at  # "./modules/docker/manifests/init.pp" (line 222, column 11) .
This is not allowed, you should only use require at # "./modules/docker/manifests/init.pp" (line 225, column 3)
```

**Comment by PierreR** [comment]
I believe `contain` is not supposed to include the resource. What it does is registered it to be included in case of a requirement.
So if `include` is basically already doing so, I guess `contain` might just be left empty ...

**Comment by PierreR** [comment]
Still it will be kind of confusing because it means the `include` behavior of `puppet` and the one `language-puppet` are semantically different (that said this whole containment story sounds like a gigantic puppet design mistake)

**Comment by bartavelle** [comment]
Will fix that in a minute. The contain bug, not the include semantics :)

**Comment by bartavelle** [comment]
I removed the spurious check, it's caused by puppet that can't differentiate `include foo` from `class { 'foo': }` (no parameters).

**Comment by PierreR** [comment]
For completion here is [the ruby doc for the contain function](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/parser/functions/contain.rb):
```
Contain one or more classes inside the current class. If any of
these classes are undeclared, they will be declared as if called with the
`include` function. Accepts a class name, an array of class names, or a
comma-separated list of class names.
A contained class will not be applied before the containing class is
begun, and will be finished before the containing class is finished.
You must use the class's full name;
relative names are not allowed. In addition to names in string form,
you may also directly use Class and Resource Type values that are produced by
```
If you believe it is closed enough to the implementation  I will close the issue.
