### ISSUE TITLE
puppetresources logs multiple times the same call ?

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#136]
While adding a placeholder for #135, I have realized that `puppetresources` seems to log several times the same call:

```
puppetresources -p . -o docker/registry_prod --hiera ./tests/hiera.yaml --pdbfile ./tests/facts.yaml -n docker
WARNING: docker/registry_prod: Contain 'docker::install', the function is not yet implemented
WARNING: docker/registry_prod: Contain 'docker::install', the function is not yet implemented
WARNING: docker/registry_prod: Contain 'docker::install', the function is not yet implemented
WARNING: docker/registry_prod: Contain 'docker::install', the function is not yet implemented
```

**Comment by bartavelle** [comment]
This is expected if this is passed over several times (for example in a define block).

**Comment by PierreR** [comment]
So if  do 
```
class test {
  include docker
}
```
I will get 4 times the log for 3 "contain" (so 12 log statement in total). Here is the init file from docker : https://github.com/garethr/garethr-docker/blob/master/manifests/init.pp#L225

Maybe it is my setting that is the culprit. I define `docker/registry_prod` in the `.tests/facts.yaml` with this line:
```
  docker/registry_prod:
    role: registry
    zone: prod
    subgroup: docker
    hostgroup: middleware
    environment: middleware_prod
```
Then the lookup is done in `manifest/site.pp` as such

```
node default {
  if $::role != undef {
    if $::subgroup != undef {
      $role_path =  "${::subgroup}::${::role}"
    } else {
      $role_path = "${::role}"
    }
    include "application::role::${role_path}"
  }
}
```

And of course the file is placed at `modules/application/manifests/role/docker/registry.pp`

So this is just /modules/application/manifest/role/${subgroup}/${role}

**Comment by PierreR** [comment]
I can even do 
```
class test {
  contain bla::bla
}
```
And I will have
```
WARNING: docker/registry_prod: Contain 'bla::bla'; the function is not yet implemented
WARNING: docker/registry_prod: Contain 'bla::bla'; the function is not yet implemented
WARNING: docker/registry_prod: Contain 'bla::bla'; the function is not yet implemented
WARNING: docker/registry_prod: Contain 'bla::bla'; the function is not yet implemented
puppetresources: File not found
```

**Comment by bartavelle** [comment]
The log message is emitted once, but is printed four times with logM ... Looks like a bug with the log library :(

**Comment by PierreR** [comment]
Well apparently I misunderstood something when I originally set up the logger ;-)
