### ISSUE TITLE
Support for ghc-7.8

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#137]
I add a travis file on my repo to check if `language-puppet` still compiles with ghc-7.8. It wasn't so I undertook a rather painful process and get it toward a green build.

https://github.com/PierreR/language-puppet
https://github.com/PierreR/language-puppet/commit/a5881203d9291b3145a02dd44f32310583cf4c96

That was fun but probably completely useless ...

For the sake of it, I could push these changes on your repository. Then I would suggest to release `1.4.1.1` (or something) and immediately drop "support" for ghc < 7.10 afterward.

What do you think ?

Would you mind opening a travis account ?

**Comment by bartavelle** [comment]
Why go though this if it is for abandoning support right away ?

I am pretty sure you and I are the only users of the package anyway :)

What is the travis account for ?

**Comment by PierreR** [comment]
Well yes let's drop it then. I will change the cabal file just to make it clear.

The travis account is to automatically compile and run the tests at each commit. But for ghc-7.10 I think the setting should be a bit different. We can let this on the side as well because ideally it should use the new docker infrastructure of travis. This is much nicer because you get caching for free. But it will not work here because the default ruby is 1.9.x, no sudo support on docker travis yet and ... rvm only gives us precompiled ruby (without the header files).

My motivation is the shiny icon ;-) It does attract newcomers (more and more people are actually expecting this kind of "feature" (automatic build) from an open source project before using it.

But well it looks like `puppet` is slowly dying so it might not worth the trouble ...

**Comment by bartavelle** [comment]
Really ? Are there alternatives that are not python DSLs ?

**Comment by PierreR** [comment]
Just the feeling that the activity around many puppetlabs modules has slowed down quite a bit. But I don't know of any serious and mature alternative yet (one that would justify a switch).

Lot's of folk bet on containers based solution where puppet plays a minor role (and would ultimately be replaced). On that front, [terraform](https://terraform.io/) looks promising.

There is even an Haskell/Go based project called [`fugue`](https://fugue.it/) but it is not open source and only supports aws.

I am also amazed by the lack of serious from puppet sometimes. The error reporting on the command line is quite bad in general and some serious bug like this [one](https://tickets.puppetlabs.com/browse/PUP-1244) for instance hasn't been ported to 3.x (while it has been created in 2013 ...)

**Comment by bartavelle** [comment]
I registered a travis account, please merge your travis file !

**Comment by PierreR** [comment]
Done. Something quite surprised me while doing it. See my note "On travis, Strict conflicts ... ". I had to hide it. It is quite weird as I has never had any problem compiling this locally.
