### ISSUE TITLE
Parser and Tokenizing instance

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#138]
`parsers` defines 
```
instance Parsec.Stream s m Char => TokenParsing (Parsec.ParsecT s u m)
```
I find it so clumsy that we need to create a [wrapper instance](https://github.com/bartavelle/language-puppet/blob/master/Puppet/Parser.hs#L73) just because we want to redefine `someSpace` from `TokenParsing`.

Is there a better way to do this so we can keep using the `Parser` synonym [defined here](https://hackage.haskell.org/package/parsec-3.1.9/docs/Text-Parsec-Text.html) ?

**Comment by bartavelle** [comment]
I don't see what you mean ?

**Comment by PierreR** [comment]
I mean I can get rid of
```
newtype Parser a = ParserT { unParser :: PP.ParsecT T.Text () Identity a}
                 deriving (Functor, Applicative, Alternative)
```
and simply use `Parser` defined in Text-Parsec. I does compile but it does not work because of the implementation of `someSpace` (that I have just removed).

But if I want to define
```
-- instance PP.Stream T.Text Identity Char => TokenParsing (PP.ParsecT T.Text () Identity)
instance TokenParsing (PP.ParsecT T.Text () Identity) where
  someSpace = skipMany (simpleSpace <|> oneLineComment <|> multiLineComment)
    where
      simpleSpace = skipSome (satisfy isSpace)
      oneLineComment = char '#' >> void (manyTill anyChar newline)
      multiLineComment = try (string "/*") >> inComment
      inComment =     void (try (string "*/"))
                  <|> (skipSome (noneOf "*/") >> inComment)
                  <|> (oneOf "*/" >> inComment)
```
Then I have an overloading error message:
```
          Overlapping instances for TokenParsing
                             (PP.ParsecT T.Text () Identity)
   arising from a use of ‘token’
```
So I can see that the only use of the wrapper is just this ...

**Comment by bartavelle** [comment]
Yes that's exactly what it i :)

Using the parser type from `parsec` means giving up on the nice combinators from the `parsers` package. I originally used it because I thought it was much nicer than `parsec`, and because it makes it easy to switch parsing engines. I wanted to try out `trifecta` for its error messages, but it turned out it was horribly slow.

In the end I really liked `parsers`, and kept it like that, even though I still use parsec underneath. I really like the tokens system. Do you really think it would be better to drop this dependency ? Perhaps with the new `megaparsec` package, but I am unsure still.

**Comment by bartavelle** [comment]
Also for reference, [this](https://github.com/bartavelle/language-puppet/blob/v0.2.1/Puppet/DSL/Parser.hs#L30-L51) is what you have to do with parsec to do the same thing.

**Comment by PierreR** [comment]
> Do you really think it would be better to drop this dependency ?
No. I am just learning trying to get a more deep understanding of the code (my ultimate goal is to fix  #134 but I feel I still need some more enlightenment to achieve it).

Thanks for the explanation. Very informative.

**Comment by bartavelle** [comment]
Also, note that the newtype business quite sucks for the expression parser ...

**Comment by PierreR** [comment]
Yep. For sure the code is simpler without the wrapper. It feels a bit awkward how the two library collide.

**Comment by PierreR** [comment]
What about using https://github.com/ekmett/parsers/blob/master/src/Text/Parser/Token/Style.hs to defined what's a comment ?

**Comment by PierreR** [comment]
> Using the parser type from parsec means giving up on the nice combinators from the parsers package

I thought `parsers` was meant to work with `parsec` transparently. What really makes it impossible to be so ?

**Comment by bartavelle** [comment]
I don't know about the Style module. I'll take a new look on this in a few days.

And you can use `parsers` transparently with any parsing library as long as you are happy about the someSpace definition :)

**Comment by bartavelle** [comment]
It turns out I don't remember why I did not go with the expression parser from `parsers`. It once had performance issues but I believe them solved since. Do you mind testing the thing I just pushed on your repositories ? Mine aren't large enough to get meaningful results ...

If there is a problem, it should be quite obvious.

**Comment by PierreR** [comment]
It works fine !

I have the feeling it should be possible to use [`buildSomeSpaceParser :: CharParsing m => m () -> CommentStyle -> m ()`](https://github.com/ekmett/parsers/blob/master/src/Text/Parser/Token/Style.hs#L109) and get rid off the wrapper type. What do you think ?

**Comment by bartavelle** [comment]
Getting rid of the wrapper type means stopping using all functions requiring `TokenParsing`, ie. the stuff [here](http://haddock.stackage.org/lts-3.7/parsers-0.12.3/Text-Parser-Token.html), and redefining them ...

**Comment by PierreR** [comment]
Well the parser would still be an instance of `TokenParsing`, no ?
https://github.com/ekmett/parsers/blob/master/src/Text/Parser/Token.hs#L818

**Comment by bartavelle** [comment]
Parsec already is, hence the newtype.

**Comment by bartavelle** [comment]
Oh ok. Parsec is an instance of TokenParsing, except its definition of `someSpace` is wrong for parsing puppet files.

**Comment by PierreR** [comment]
Yep and I was thinking this could be fixed by the provided `buildSomeSpaceParser`  from Text.Parser.Token.Style

**Comment by bartavelle** [comment]
I just tried `megaparsec`, and it does indeed give better error messages. For this:

    node 'a.b' {
      file { 'aasdqqsd':
        sdqq
        ;
      }
    }

Parsec says:

    puppetresources: parse error:"/tmp/tst.pp" (line 4, column 5):
    unexpected ";"
    expecting "#", "/*" or "=>"

Megaparsec says:

    puppetresources: parse error:"/tmp/tst.pp" line 4, column 5:
    unexpected ';'
    expecting "=>" or rest of Assignment key

**Comment by bartavelle** [comment]
How could that help get rid of the newtype ? It looks like it helps writing newtypes ...

**Comment by bartavelle** [comment]
See [here](https://github.com/bartavelle/language-puppet/blob/567579d9b2e7ced4a5cabda445258f0e42831bbf/Puppet/Parser.hs#L104-L107). (This is the megaparsec branch, with even more boilerplate ...)

**Comment by PierreR** [comment]
> How could that help get rid of the newtype ? It looks like it helps writing newtypes ... 

;-)
I would expect everything to be working without the `newtypes`. Then instead of writing an instance for TokenParsing (as you said there is already one), I would try to use  `buildSomeSpaceParser` . `PP.ParsecT T.Text () Identity a` is an instance of `CharParsing`. But I guess my hope is just to high ;-)

**Comment by bartavelle** [comment]
Then you'll have to redefine `symbol`, `comma`, etc. And also `identifier`. This would be just like using plain old `parsec`. Perhaps with `megaparsec` this is more bearable, and I will check it a bit, but I thought that the newtype business was a lot less boilerplate than the parsec solution.

**Comment by bartavelle** [comment]
Ok I am not sure of what you mean by *I would try to use `buildSomeSpaceParser . PP.ParsecT T.Text () Identity` a is an instance of CharParsing*.

**Comment by PierreR** [comment]
Well I probably misunderstand it but I thinking about taking our final Parser (which would be of type `TextParsec.Text.Parser`), use it as the first input to `buildSomeSpaceParse`. Then provide `CommentStyle` (that would replace the current `someSpace` implementation) and I would get  the final parser to expose.

**Comment by PierreR** [comment]
Something like this:

`runPParser p = PP.parse (buildSomeSpaceParse p commentstyle)`

Just thinking aloud ...

**Comment by bartavelle** [comment]
Oh well, that wouldn't work ! `buildSomeSpaceParse` is just a convenient way to build the `lexeme` function. It skips the comments *and* the given inner parser. Also see that its return type is `m ()`.

So basically you use it like that:

    lexeme p = p *> buildSomeSpaceParse skipspaces commentstyle
    symbol = p . try . string
    comma = symbol ","
    reserved s = try $ do
        m <- string s
        when (m `elem` ["reserved1", "reserved2","if","then","else"]) $ fail "reserved"
        return m

So you need it all over the place when defining the parser ...

**Comment by bartavelle** [comment]
Edit, updated the previous comment has it made no sense :)

**Comment by PierreR** [comment]
Thanks for  the explanation.

I had a go with the `megaparsec` branch. Everything seems to work just fine. So it is really up to you.

**Comment by bartavelle** [comment]
I tried throwing out all the stuff from parsers and now nothing parses ;) I'll try again in a few days.

**Comment by PierreR** [comment]
The `megaparsec` branch looks promising.

I am doing the change on master to avoid conflict but I think we can simplify  `variableReference` as such (the check is already made in variableName):
```
variableReference :: Parser T.Text
variableReference = char '$' *> variableName
```

**Comment by bartavelle** [comment]
Yes that would work !

I tried the megaparsec branch the other day when looking for the `contain` function inclusion. I found a bug where it didn't parse your sample properly. Can you run the megaparsec branch on all your files ?

**Comment by PierreR** [comment]
Yep I will do that tomorrow.

**Comment by PierreR** [comment]
Many `lexer` tests are failing with such a message:
```
9 tests/lexer/rawresref.pp:5:5:
unexpected '}'
expecting "undef", '"', '$', '[', Boolean, or Literal Value
```

**Comment by PierreR** [comment]
Trying to investigate a bit more:
This parses successfully:
```
class test {
    file {
        "/etc/udp2log/${name}":
            require => Package[udplog]
    }
}
```
This does not (after adding `;`):

```
class test {
    file {
        "/etc/udp2log/${name}":
            require => Package[udplog];
    }
}
```
In other words:
```
λ> parse (puppetParser <* eof) "Test" "file {\"name\":\nrequire => Package[bob]\n}"
OK

λ> parse (puppetParser <* eof) "Test" "file {\"name\":\nrequire => Package[bob];\n}"
Left Test:3:1:
unexpected '}'
expecting "undef", '"', '$', '[', Boolean, or Literal Valuey

```

**Comment by PierreR** [comment]
There is something I quite don't understand with `megaparsec´
```
λ> parse ((token (string "hello") `sepBy1` comma) <* optional (symbol ";")) "test" "hello, hello;"
Right ["hello","hello"]
λ> parse ((token (string "hello") `sepBy1` comma) <* optional (symbol ",")) "test" "hello, hello,"
Left test:1:14:
unexpected end of input
expecting "hello"
```
As a consequence `sepComma` does not really do what I would expect ...

**Comment by bartavelle** [comment]
Well spotted, this is indeed surprising !

**Comment by bartavelle** [comment]
and `sepEndBy1` is buggy too !

**Comment by bartavelle** [comment]
I opened an issue in the megaparsec repo, but will provide a working implementation in the meantime.

**Comment by bartavelle** [comment]
All tests are now OK.

**Comment by PierreR** [comment]
I have checked on my side and everything works fine.

Shall we merge with master ?

**Comment by PierreR** [comment]
I have remove the unused prim `_PParser`. Is it alright ?

I can do the merge if you are ok with it.

**Comment by bartavelle** [comment]
Yes that would be nice, thanks !
