### ISSUE TITLE
support template() with two arguments

### ISSUE THREAD

**Issue by sylvainfaivre** [bartavelle/language-puppet#142]
Salut, quoi de neuf ?

Avec la release 1.1.4, pour parser un fichier de la release 1.8.0 de https://forge.puppetlabs.com/puppetlabs/apt, j'ai l'erreur : 

ERROR: (allnodes) template(): Expects a single argument at # ./modules/apt/manifests/init.pp:93:10

Cela fait référence au code suivant : 

file { '/etc/apt/apt.conf.d/15update-stamp':
    ensure  => 'file',
    content => template('apt/_header.erb', 'apt/15update-stamp.erb'),
    group   => 'root',
    mode    => '0644',
    owner   => 'root',
}

**Comment by PierreR** [comment]
This is a bug.
Just for reference:
Here is the puppet spec:
https://github.com/puppetlabs/puppet/blob/d2199af906fa5ca19ec0c37c82794934ea4fb4b5/lib/puppet/parser/functions/template.rb#L13
And the Haskell code:
https://github.com/bartavelle/language-puppet/blob/31b05feecc03d2ad03d02cdf94f75566c27aa11b/Puppet/Interpreter/Resolve.hs#L470-L471

**Comment by bartavelle** [comment]
This should work now !

**Comment by sylvainfaivre** [comment]
fix confirmed
