### ISSUE TITLE
parsing error - unexpected '?' 

### ISSUE THREAD

**Issue by sylvainfaivre** [bartavelle/language-puppet#143]
Avec la release 1.1.4, pour parser un fichier de la release 2.2.0 de https://forge.puppetlabs.com/puppetlabs/apt, j'ai l'erreur : 

ERROR: (allnodes) ./modules/apt/manifests/init.pp:80:51: 
unexpected '?' 
expecting '}' or Statement at # ./modules/it/manifests/baseconfig/aptcfg.pp:3:13

Cela fait référence au code suivant : 

$sources_list_content = $_purge['sources.list'] ? {
    true    => "# Repos managed by puppet.\n",
    default => undef,
}

**Comment by PierreR** [comment]
Would you mind testing with the latest master  (the parser has been changed to use `megaparsec`) ? You can easily do this using `stack`.

**Comment by sylvainfaivre** [comment]
Well actually, we have a complicated build setup, and at the moment our tools can only build the latest release from https://github.com/bartavelle/language-puppet/releases
I will try to build the latest master on another system, and let you know if I succeed.

**Comment by PierreR** [comment]
In case it helps I have a docker that bundles the tool at the latest master (it also inclues  a check_lint command):

```
docker pull pierrer/puppetresources:v1.1.4-k
```

**Comment by sylvainfaivre** [comment]
OK, I was confused by the way our build systems works, the resulting package is versioned 1.1.4 but it is actually compiled from the master branch.
This is up to date to the latest commit 3e916fcd3db6e81bd83eb2e6b9b2173ef91c306e
so the bug is present in current code.

**Comment by bartavelle** [comment]
The problem is that selectors only work with variables currently. I will add support for lookups.

**Comment by bartavelle** [comment]
It turns out it should be more general : https://docs.puppetlabs.com/puppet/latest/reference/lang_conditional.html#control-expressions-1

But I will only fix this for lookups for now.

**Comment by bartavelle** [comment]
See 7bb0a8d52b5a19bb7daa8d0474c5f479077b2489

**Comment by sylvainfaivre** [comment]
Fixed confirmed for the case I encountered. You can close the bug if you want, or keep it open to track the more general case.
