### ISSUE TITLE
hrubyerb.rb syntax error

### ISSUE THREAD

**Issue by sylvainfaivre** [bartavelle/language-puppet#144]
/usr/local/bin/hrubyerb.rb:80: syntax error, unexpected ',', expecting '='
    def initialize(context,variables,filename='x',stt,rdr)

fixed by setting default values on line 80 : 
-    def initialize(context,variables,filename='x',stt,rdr)
+    def initialize(context,variables,filename='x',stt='x',rdr='x')

This is using ruby 1.8.7.352-2ubuntu1.6

**Comment by bartavelle** [comment]
Is the file in `/usr/local/bin/hrubyerb.rb` identical to the one shipped with language puppet ? https://github.com/bartavelle/language-puppet/blob/master/ruby/hrubyerb.rb

**Comment by sylvainfaivre** [comment]
Yes it is identical.

Formatting was bad in my post, I meant : 
This can be fixed by setting default values on line 80 :
* original version : 
    def initialize(context,variables,filename='x',stt,rdr)
* fixed version : 
    def initialize(context,variables,filename='x',stt='x',rdr='x')

**Comment by bartavelle** [comment]
I don't currently have a 1.8 version around, but I believe it might be caused by the fact that arguments with default values must be "last" in the function declaration.

Does that give a syntax error ?

    def initialize(context,variables,stt,rdr,filename='x')

**Comment by sylvainfaivre** [comment]
You're right, that works fine !

**Comment by bartavelle** [comment]
I will push a fix.
