### ISSUE TITLE
Could not resolve variable $::settings::strict_variables

### ISSUE THREAD

**Issue by sylvainfaivre** [bartavelle/language-puppet#145]
program output : 
ERROR: (allnodes) Could not resolve variable $::settings::strict_variables in context settings or root at # ./modules/apt/manifests/params.pp:9:3

offending line in manifest line is : 
  if ! $::settings::strict_variables {

**Comment by PierreR** [comment]
You could add this variable to your tests/defaults.yaml file.
Here is an example of possible customization:
See https://github.com/bartavelle/language-puppet/blob/master/tests/defaults.yaml
