### ISSUE TITLE
Feature Versionable is required for the current configuration

### ISSUE THREAD

**Issue by sylvainfaivre** [bartavelle/language-puppet#148]
```
ERROR: (server.fqdn) : Invalid resource package {
  innotop: # ./modules/percona/manifests/init.pp:83:9 server.fqdn [Scope [class percona]]
    ensure   => latest,
    provider => dpkg,
    source   => /opt/debs/innotop_1.9.1_all.deb,
    require  => File[/opt/debs/innotop_1.9.1_all.deb],
    require  => Class[percona];
}
Feature Versionable is required for the current configuration at # ./modules/it/manifests/ituser.pp:11:16
```

Maybe puppetresources is confused because our class percona takes a $version parameter ?

**Comment by bartavelle** [comment]
The error comes from the fact that you used "latest` with the `dpkg` provider, as it [doesn't support the versionable feature](https://docs.puppetlabs.com/references/latest/type.html#package-provider-dpkg).

I don't know if the docs are very clear on this, but I believe it should work with just `present` ...

**Comment by sylvainfaivre** [comment]
ok, my bad.

**Comment by bartavelle** [comment]
To be clear this error is my personal interpretation of the way puppet works. I might be wrong here ...

**Comment by sylvainfaivre** [comment]
Well since the dpkg provider doesn't support versionable, it would make sense if `ensure   => latest` was not supported.

But I just tried it, and Puppet accepts either `present` or `latest` (but not some other value).

Here's the output with each value : 
```
Notice: /Stage[main]/Percona/Package[innotop]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Percona/Package[innotop]/ensure: ensure changed 'purged' to 'latest'
Error: Failed to apply catalog: Parameter ensure failed on Package[innotop]: Provider must have features 'versionable' to set 'ensure' to 'lolol' at /etc/puppet/modules/percona/manifests/init.pp:80
```

So you might want to update puppetresources to make it accept `ensure   => latest` for dpkg provider too.

**Comment by bartavelle** [comment]
Just pushed a change that would set the error when ensure is not set to some known word (latest, purged, absent, installed, present, held).
