### ISSUE TITLE
Change the default package provider

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#150]
Is there a way to change the default package provider ?
https://github.com/bartavelle/language-puppet/blob/master/Puppet/NativeTypes/Package.hs#L68

**Comment by bartavelle** [comment]
You mean picking it based on the facts ? It would require refactoring the whole post-test thingie so that it somehow has access to the state, or at least to the facts.

**Comment by PierreR** [comment]
I might be able to fix my problem with a PR ;-)
According to the [doc](https://docs.puppetlabs.com/references/latest/type.html#package-provider-apt), the `apt` providers does support `install_options`. So I guess I just need to add [here.](https://github.com/bartavelle/language-puppet/blob/master/Puppet/NativeTypes/Package.hs#L25)
