### ISSUE TITLE
Little refactoring proposition

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#154]
[Here](https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter.hs#L205), why not using the hashmap function so that:
```
 verified <- ifromList . map (\r -> (r ^. rid, r)) <$> mapM validateNativeType (toList real)
```
becomes 
```
 verified <- HM.fromList . map (\r -> (r ^. rid, r)) <$> mapM validateNativeType (HM.elems real)
```
The first change is about replacing `ifromList` with `HM.fromList`. I can see these two are not equivalent. `ifromList` ignores the duplicates and `HM.fromList` overrides the old value with the new one but I am under the impression that there is no duplicate at this stage.

The second change seems more straigthforward. It is a bit hard to tell what kind of treatment we've got from `Foldable.toList` whereas it is easy to reason about `HM.elems`. Aren't these two equivalent ?

**Comment by bartavelle** [comment]
These are from a time when I experimented switching between `Map` and `HashMap`. I don't have a strong opinion on the subject, but I personnaly like `toList` better than `elems`, as it is difference in `Data.Map` and I can't ever remember which is which ..

**Comment by PierreR** [comment]
Ah alright. Thanks for the explanation. I don't mind keeping `toList` but for consistency sake then I would change the call to `HM.elems` 2 lines below ;-)

**Comment by bartavelle** [comment]
Haha :) It would be indeed much better to have a consistent code, so if you feel like fixing this, go ahead by all means! Either version is fine by me.

**Comment by PierreR** [comment]
Actually what I find pretty weird with `toList` is the lack of symmetry with `fromList` ...One need a tuple of (key,val) and the other one just keep the `val`.

**Comment by bartavelle** [comment]
Yeah, that's why I called my wrapper `ifromList`, it is `fromList` that is weird !

**Comment by bartavelle** [comment]
The real problem is that [this](http://haddock.stackage.org/lts-3.15/base-4.8.1.0/GHC-Exts.html#t:IsList) is distinct from [this](https://hackage.haskell.org/package/base-4.8.1.0/docs/Data-Foldable.html#v:toList) :(
