### ISSUE TITLE
Edgemaps removed from WireCatalog in json

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#155]
I don't quite understand what [the filter here](https://github.com/bartavelle/language-puppet/blob/master/progs/PuppetResources.hs#L212-L213) is doing but it does wipe out all the edges from the json output for me. So in the json output, edges is always `[]` but if I remove the filter I get them back.

What does it mean to be a `knownEdge` ?

**Comment by bartavelle** [comment]
IIRC the edgemap should only contain edges that can't be inferred from the other parts of the catalog. This is experimental code though, and I only tested it a couple of times as a real puppet server (it seemed to work!).

**Comment by PierreR** [comment]
Ah, nice.
Just push a commit that moves the utils function from `Puppet.Interpreter.Type` to a separate module `Puppet.Interpreter.Utils`  Hope you don't mind ;-). The module was quite big with all these functions around.

**Comment by bartavelle** [comment]
Should be for the best.
