### ISSUE TITLE
stdlib :: merge more than two hash

### ISSUE THREAD

**Issue by jfroche** [bartavelle/language-puppet#159]
We have the usecase to merge more than two hash (3 in fact)

```haskell
merge :: [PValue] -> InterpreterMonad PValue
merge [PHash a, PHash b] = return (PHash (b `HM.union` a))
merge [a,b] = throwPosError ("merge(): Expects two hashes, not" <+> pretty a <+> pretty b)
merge _ = throwPosError "merge(): Expects two hashes"
```

can you do the same for 3 hash or even better merge an infine list of PHash ?

ruby implementation is here: https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/lib/puppet/parser/functions/merge.rb

**Comment by bartavelle** [comment]
Just pushed a fix. Do you mind checking of its behavior is consistent with how puppet works (with regards to key collisions) ?

**Comment by jfroche** [comment]
I will look with @PierreR to add a unittest for this one

**Comment by bartavelle** [comment]
I copied the unit tests from Puppet and found a regression. This is now fixed.
