### ISSUE TITLE
using JSON library in a template

### ISSUE THREAD

**Issue by jfroche** [bartavelle/language-puppet#164]
we are using JSON in an inline erb template.

``` puppet
$real_content = inline_template('<%= JSON.parse(@json_content).to_yaml + "\n" %>')
```

Or I can try to implement this, do you have a similar use case which is already present in the code ? 
I looked in hrcallfunction but don't get where the FromRuby resolve such a namespace (JSON).
Thank you !

**Comment by bartavelle** [comment]
It might be possible to implement easily, if you want to give it a try. You would need to have `JSON` accessible in the Erb namespace. Look into `ruby/hrubyerb.rb`, how the `to_yaml` function is made available, so that you can export the `JSON` thingie.

Unfortunately I am not really knowledgeable about ruby to know if there is a nicer way to do this ..

**Comment by jfroche** [comment]
json is an external ruby library. hruby can handle this ?

I have added a `require 'json'` and get the following traceback:

```
ERROR: (default) Could not load /code/.stack-work/install/x86_64-linux/lts-3.17/7.10.2/share/x86_64-linux-ghc-7.10.2/language-puppet-1.1.4.1/ruby/hrubyerb.rb
cannot load such file -- json
/code/.stack-work/install/x86_64-linux/lts-3.17/7.10.2/share/x86_64-linux-ghc-7.10.2/language-puppet-1.1.4.1/ruby/hrubyerb.rb:4:in `require'
/code/.stack-work/install/x86_64-linux/lts-3.17/7.10.2/share/x86_64-linux-ghc-7.10.2/language-puppet-1.1.4.1/ruby/hrubyerb.rb:4:in `<top (required)>'
```

Also the json gem includes c extensions

**Comment by bartavelle** [comment]
Hum it seems I forgot of this issue! You will have to alter the hrubyerb.rb file and add your require on top, then add aliases to all functions you need to call in the Scope objects (look at yaml / function_to_yaml).

**Comment by bartavelle** [comment]
Do not hesitate sending me a PR if this works!

**Comment by bartavelle** [comment]
(Also you need to stack install everytime you alter the ruby file, or edit it in its installed location)

**Comment by PierreR** [comment]
Just adding 'require json' make this to work:

```
class application::test {
  $json_content = "{\"hello\": 2}"
  $real_content = inline_template('<%= JSON.parse(@json_content).to_yaml  %>')
  notify{"${real_content}":}
}
```
@jfroche let us know if this is not solving your problem
