### ISSUE TITLE
Resource collector should override resource attributes

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#165]
From the puppet documentation:
> When given a block of attributes and values, a collector will set and override those attributes for every resource (virtual or not) that matches its search expression.

**Comment by PierreR** [comment]
Actually it is even worse: attribute resource collector are never added at all.
```
class test {
  group {'test1':
    ensure => present,
  }
  group {'test2':
    ensure => present,
  }
  user {'test':
    ensure => present,
    groups => 'test1'
  }

  User <| title == 'test' |> { groups => "test2", uid => 100 }
}
```
Gives back a user without `uid`:
```
user {
  test: # ./modules/application/manifests/role/sonarqube.pp:8:9 sonarqube_prod [Scope [class application::role::sonarqube]]
    allowdupe            => false,
    attribute_membership => minimum,
    auth_membership      => minimum,
    ensure               => present,
    groups               => [test1],
    key_membership       => minimum,
    managehome           => false,
    membership           => minimum,
    name                 => test,
    profile_membership   => minimum,
    role_membership      => minimum,
    system               => false,
    require              => Class[test];
}
```

**Comment by bartavelle** [comment]
Oh this is very bad :(

Do you think you would have time to write the corresponding (failing) tests ? I will take a stab at the problem during the week end.

**Comment by bartavelle** [comment]
Looks like you already did!

**Comment by PierreR** [comment]
>  I will take a stab at the problem during the week end.

Cool. Thanks. Unfortunately I still feel I cannot solve this on my own (but hopefully I am getting there eventually). 

While you are at it, if it makes sense to split `addAttribute` into different functions like `addAttribute`, `checkAttribute`, `replaceAttribute` (instead of using the `OverrideType` datatype) I would suggest to do so (but maybe this is not advisable for some reason ?)

**Comment by PierreR** [comment]
As a side note, something I still quite don't understand is why we do the [expandDefine](https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter.hs#L127) in the `finalize` function ? Some more source comment would be helpful I think.

**Comment by bartavelle** [comment]
It's because you need to apply default values and other overrides *before* computing wha's in the define. And yes, this would be nice to comment on!

**Comment by bartavelle** [comment]
I just pushed a tentative fix, can you check if it behaves as you wish ?
