### ISSUE TITLE
size() function for a string

### ISSUE THREAD

**Issue by jfroche** [bartavelle/language-puppet#166]
```ruby
size("x${priority}")
```
returns
```
size(): Expects a hash, not x10
```

but the ruby implementation works for string, array, hash (https://github.com/puppetlabs/puppetlabs-stdlib#size).

**Comment by bartavelle** [comment]
I just pushed a quick tentative fix

**Comment by bartavelle** [comment]
I added unit tests from the ruby stdlib definitions to this function. I now expect it to work!
