### ISSUE TITLE
hiera_array does not fail when the key is not found

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#168]
While `hiera(`'unknow')` would fail; `hiera_array` won't.

**Comment by bartavelle** [comment]
Just pushed 9dcdcfafe065aec59127c8a91a16253a84da6e3a which should fix this

**Comment by bartavelle** [comment]
Is that ok for you?

**Comment by PierreR** [comment]
I will check it by Tuesday.

**Comment by PierreR** [comment]
Works like a charm. Thanks.
