### ISSUE TITLE
stdlib :: assert_private

### ISSUE THREAD

**Issue by jfroche** [bartavelle/language-puppet#171]
https://github.com/danzilio/puppet-letsencrypt fails on this error:

```
Unknown function: assert_private 
```

Can you implement this method easily ?

ruby code:
https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/lib/puppet/parser/functions/assert_private.rb

**Comment by bartavelle** [comment]
This is horrible :(

I suppose this could be done. I am unfortunately quite busy for the next two weeks so I won't be able to work on it quickly ...

If you want to try your hand, all data should be in the "scope" field of the state.

**Comment by bartavelle** [comment]
I just pushed a tentative implementation. Does it work for you?

**Comment by jfroche** [comment]
It doesn't complain anymore about the unknown function.
I tested with a class (using include) which contain the assert_private outside the module and language-puppet and it complains.

Thank you !
