### ISSUE TITLE
Support  resource duplication for class, include when order this way alike Puppet

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#172]
In Puppet this works
```
class { 'jenkins':}
include jenkins
```
but this won't:
```
include jenkins
class { 'jenkins':}
```

Would it be possible to support the first case in `language-puppet` ? I have had an issue upgrading the puppetlabs jenkins module because `language-puppet` will throw an error in the first case (accepted by Puppet).

See https://github.com/jenkinsci/puppet-jenkins/pull/490

**Comment by bartavelle** [comment]
It should work, this clearly is a bug! I am unfortunately busy for the next two weeks, so I won't be able to fix this quickly ...

**Comment by bartavelle** [comment]
I just added tests to check for this. It works in the test-suite, so I suppose there is something more complex afoot. Is there some hiera default data for this class ?

**Comment by PierreR** [comment]
I will check it out tomorrow but shouldn't the third case fail ? My understanding is that 
```
include jenkins
class { 'jenkins':}
```
would fail in Puppet (so I guess it should fail as well with language-puppet) but maybe this is some design flaw that has been fixed in recent version of Puppet ?

Anyhow this is from a book that stated:
> .. you cannot use the resource style declaration after a class has been declared using `include`. This is because the parameters are then determined to assume their default values and a `class {'name':}` declaration clashed with that

**Comment by bartavelle** [comment]
Well this sucks, as order shouldn't be important in Puppet, right? Except for variables, function calls, etc. :)

**Comment by bartavelle** [comment]
Just pushed a patch that completely alters the behaviour. It will make `include` style always succeed. As I don't know if there is an official parsing order, I don't know if language-puppet is compliant.

**Comment by PierreR** [comment]
Well yes that why I wish for a better designed configuration DSL ;-)
I am going to check all these cases in 3.8.4 with the future parser enabled and let you know.

**Comment by PierreR** [comment]
In the meanwhile I will take the new change and see if the puppetlabs `jenkins` module is happy.

Thanks  for the quick patch !

**Comment by PierreR** [comment]
Everything works as expected so far. I will be closing the issue for now.
Thanks again.
