### ISSUE TITLE
Hash to string convertion

### ISSUE THREAD

**Issue by jfroche** [bartavelle/language-puppet#173]
Hello,

We would like to print a hash during a puppet run with something similar to this code:
```
  $foo = { 'a' => 'b' }
  notify {"test: ${foo}":}
```

but we get a failure:

```
Problem with <hostname> : Don't know how to convert this to a string:
{  a => b} at # ./modules/<module>/manifests/init.pp
```

I tried this in Resolv.hs:

```haskell
resolvePValueString (PHash h) = return (pretty h)
```

but pretty does not return a String, just a Doc. I didn't find a way to render the Doc as a String

Thank you

**Comment by bartavelle** [comment]
Argh don't do that! That will break all the code that uses this function to validate that the input arguments are indeed not strings.

Is that something you would need only in language-puppet? If so, I can add a special function for this purpose (like the `dumpinfos` function that doesn't exist in puppet).

**Comment by PierreR** [comment]
I would think one problem here is the fact that the default "name" params doesn't not behave as the "message" params, validation wise. So:
```
  $foo = { 'a' => 'b' }
  notify {"testme":
    message => $foo
  }
```
Would issue the following error:
```
Parameter message should be a string, and not {  a => b} at # ./modules/tool/manifests/key_value.pp:40:9
```
Should't `string_s` be fixed to allow `hash` as well as `array` ? Then if somehow we could apply the same rule for the default name params this issue would be solved.

**Comment by bartavelle** [comment]
Well it would be easy to remove all kind of verification for the message argument. Is that what is expected ? I only recently discovered it could be an array of strings ...

**Comment by PierreR** [comment]
Sure but is there a way to remove all kind of verification for the name of the notify resource (which usually serve as message) as easily ?

**Comment by bartavelle** [comment]
Not it's not, the name has to be a string. Also in the provided example, it's even worse, it's in the string interpolation code that the special case should be found.

It is probably doable, but is that a good idea ?

**Comment by PierreR** [comment]
@jfroche Are you ok with the fix ?
