### ISSUE TITLE
Known users and groups not used when checking if a relation exists ?

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#177]
It seems that `prefKnownusers`  and `prefKnowngroups` are not used by [`checkExist`](https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter.hs#L280).

As a consequence if I use a known users or groups in a requirement `puppetresources` would complain with for instance:
```
Unknown resource Group[docker] used in the following relationships: Group[docker] -> User[jenkins]
```

This came to a surprise as I would expect such a problem to come up earlier.

**Comment by bartavelle** [comment]
IMO this is a different use case! Doesn't puppet complain about this unknown resource?

**Comment by PierreR** [comment]
Oh yes you are right ... This is always confusing me ;-)
