### ISSUE TITLE
 InvalidTextualPosition when trying pdbquery remote snapshot

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#180]
I have just committed 8c4448168bb9 to fix a parsing problem with the `snapshot` command. I have now this error:
```
pdbquery -l puppetdb.sandbox.srv.cirb.lan:8080 -t remote snapshot ~/testdb.yaml
pdbquery: InvalidTextualPosition "null" 0 (-1)
```
I do have a file `testdb.yaml` that looks correct but it stops at 
```
    type: Other
    physicalprocessorcount: '2'
    clientversion: '3.8.6'
    serialnumber: VMware-42 14 1 
    blockdevice_sda_vendor: VMware
    ipaddress_lo: '

```
I don't know why for this specific node I have got this error. Any idea ?

**Comment by bartavelle** [comment]
Can you reproduce the queries with curl and share that information?

**Comment by PierreR** [comment]
The error occurs at the facts level. Do you think it is really useful to see the `curl` for the node that fails (curl 'http://puppetdb.sandbox.srv.cirb.lan:8080/v3/nodes/jenkinsmaster.sandbox.srv.cirb.lan/facts/) ?

Here is more information that could be helpful:
* The result of a curl query for facts (directly to the puppetdb) seems pretty OK to me
* The failing entry is the last node
* I have run it again today and it does not fail at the same place but just above so I now have :  
```
    selinux: 'false'
    is_pe: 'false'
    blockdevice_sda_model: Virtual disk
    typ
```
The file has `49137` of size and stop at line `1190` (just 10 nodes)

Could it be a memory/lazy loading problem while writing the file ?

**Comment by bartavelle** [comment]
The output is misleading as it probably fails after what is actually written (due to buffering). The actual response from the web server would indeed be useful to debug this ...

This is my public key https://pgp.mit.edu/pks/lookup?op=get&search=0x960CAA9B835FAF50 in case you'd like to share the facts.

**Comment by PierreR** [comment]
[facts.zip](https://github.com/bartavelle/language-puppet/files/252517/facts.zip)
Here are three encrypted files:
 *  the complete testdb.yaml
 *  the result of `(curl 'http://puppetdb.sandbox.srv.cirb.lan:8080/v3/nodes/jenkinsmaster.sandbox.srv.cirb.lan/facts/`
 * the result of  `pdbquery dumpfacts`

There should be no secret in these files but it is always nice to play a bit with `gpg` ;-)

**Comment by bartavelle** [comment]
`jenkinsmaster.curlfacts` doesn't look like a list of facts, but like a list of resources

**Comment by PierreR** [comment]
You're right. This should be right:
[jenkinsmaster-curlfacts.zip](https://github.com/bartavelle/language-puppet/files/252660/jenkinsmaster-curlfacts.zip)

**Comment by PierreR** [comment]
I actually don't understand why I have `certname` for every key in there but well ...

**Comment by bartavelle** [comment]
because you can query facts for more than one host

**Comment by bartavelle** [comment]
This is weird, this is properly read by language puppet, and all facts have string values. What happens if you try the `snapshot` command with a new puppetdb file ?

**Comment by bartavelle** [comment]
If it works it means it can't read the testdb file, which either means something changed between versions or that the deserialization code isn't right.

**Comment by PierreR** [comment]
The first time (deleting `testdb.yaml`) I have got this error:
```
~ → pdbquery -l puppetdb.sandbox.srv.cirb.lan:8080 -t remote snapshot ~/testdb.yaml
pdbquery: InvalidTextualPosition "null" 0 (-1)
```
The produced file is obviously wrong (this is the file I sent with the archive). So the second time it fails with:
```
# second time
~ → pdbquery -l puppetdb.sandbox.srv.cirb.lan:8080 -t remote snapshot ~/testdb.yaml
pdbquery: puppetdb load Could not parse /home/pierre/testdb.yaml: could not find expected ':' while scanning a simple key at line 1193, column 0
```

**Comment by bartavelle** [comment]
I should have checked earlier, but InvalidTextualPosition is a megaparsec error. This isn't a YAML/JSON problem !

**Comment by bartavelle** [comment]
Does the thing I just pushed help ?

**Comment by PierreR** [comment]
Nope. It doesn't seem to make any difference.

**Comment by bartavelle** [comment]
This has something to do with `newPos` being used with line or column numbers less than 1.

**Comment by bartavelle** [comment]
There was a brainfart in the previous fix. Must be much better now.

**Comment by PierreR** [comment]
Great it works ! Thanks.
