### ISSUE TITLE
No error (and strange output) when using unknown var in template

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#181]
Given
```
class application::role::test {
  file {
    "/test.txt":
      ensure  => present,
      content => template('application/test.erb')
  }
}
```
and  file test.erb is:
```
key = <%= @myunknownvar %>
key = <%= myunknownvar %>
```
`puppetresources [...] -n /test/txt --showcontent` will produce: 
```
key = 
key = -2.000000000194419
```
I am using ruby 2.3 but I am pretty sure it also fails on debian jessie with ruby 2.1.5.

**Comment by bartavelle** [comment]
Found the problem with the double value, and just released a new version of hruby. It autoclosed with the push, but it really will take a few minutes until the package is on stackage ...

**Comment by PierreR** [comment]
It works nicely. Thanks so much for the quick fix.
