### ISSUE TITLE
ensure_resource second argument could be an array

### ISSUE THREAD

**Issue by tbrouhier** [bartavelle/language-puppet#193]
Hi there,

language-puppet does not support _ensure_resource to have a second argument different from a String (interpreter.hs). 

This make tests with puppet-jenkins module 1.7.0 fail as they are passing an array. See following snippets: 

  ```
class jenkins::params {
...
$default_plugins = [
    'credentials', # required by puppet_helper.groovy
  ]
```

```
class jenkins::config {
...
ensure_resource('jenkins::plugin', $::jenkins::params::default_plugins)
```
The function comes from stdlib and reference is here: https://github.com/puppetlabs/puppetlabs-stdlib#ensure_resource

Cheers,
Thomas

**Comment by bartavelle** [comment]
I can't really look at it right now, but I'll try to fix this next week.

**Comment by bartavelle** [comment]
Is that better?

**Comment by tbrouhier** [comment]
Yes, it did the trick. Thanks.

**Comment by tbrouhier** [comment]
Could you create a new release on Hackage, please?

**Comment by bartavelle** [comment]
done
