### ISSUE TITLE
Removing stack.yaml ?

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#194]
Is it ok if I rename `stack.yaml` into stack-template.yaml  or something like that ?

The reason for this change is the fact that the file is often out-of-dated and conflicts with my nix setting.

**Comment by PierreR** [comment]
Another better name would be stack-8.0.yaml

**Comment by PierreR** [comment]
Well with the hope that stackage does not require such a file ...

**Comment by bartavelle** [comment]
`stack-8.0.yaml` is good to me. Stackage doesn't require the file to be present.
