### ISSUE TITLE
Unknown function: sprintf

### ISSUE THREAD

**Issue by tbrouhier** [bartavelle/language-puppet#195]
The _sprintf_ function is not recognized by puppet-language. Could you add support for it? 

The error: 
`Unknown function: sprintf at...`

An example of a call:
`notice(sprintf("INFO: make sure you install the following plugins with your code using this module: %s",join($::jenkins::params::default_plugins,',')))`

Puppet reference: https://docs.puppet.com/puppet/latest/function.html#sprintf

Cheers,
Thomas

**Comment by bartavelle** [comment]
That's a longish change. I won't probably have time for it in the close future ..

**Comment by tbrouhier** [comment]
Ok, thanks for the feedback. I will see with Pierre if he can help.

**Comment by PierreR** [comment]
I can provide a minimal implementation that works for our use case (and complete when needed) and looks like so : 
```
-- | TODO: implement sprintf
sprintf :: [PValue] -> InterpreterMonad PValue
sprintf (PString x0:PString x1:_) = return $ PString (T.pack (Text.printf (T.unpack x0) (T.unpack x1)))
sprintf args = throwPosError ("sprintf(): expected multiple arguments, not" <+> pretty args)
```
@bartavelle is there a `printf` (c compatible) version out there that works better with `Data.Text` ?

If I understand this right, this kind of function needs to go to the `Stdlib` module (even if there aren't coming from the `stdlib` puppetlabs module).

**Comment by bartavelle** [comment]
It can go to `Stdlib`, but I'm ok with it being core. Please note the function is not total, and can crash the interpreter. It would be nice to catch exceptions here.

**Comment by PierreR** [comment]
by 'core' do you mean as a `mainFunctionCall ` ? I was under the impression that those would need to return resources while we need to return a string value here.

**Comment by bartavelle** [comment]
resolveFunction' in Puppet.Interpreter.Resolve

**Comment by PierreR** [comment]
I might be missing something this but it looks like the implementation of `catchError` in the InterpretMonad is a bit bogus:
https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter/IO.hs#L82
I doesn't seem to give a change to deal with the exception.
So this code won't work as expected
```
-- | TODO: implement sprintf
resolveFunction' "sprintf" (PString x: PString x0: _) = do
  let args = x0
      handle0 e = throwPosError ("spintf arg invalid: " <> ttext args <> line <> pretty e)
  fval <- catchError (pure $ Text.printf (T.unpack x) args) handle0
  pure $ PString (T.pack fval)
```

**Comment by PierreR** [comment]
As an extra note, do you mind if I add : 
```
instance Pretty PrettyError where
  pretty = getError

```

**Comment by bartavelle** [comment]
I should have just let it be `MonadThrow` instead of `MonadError`. I am fleshing out the catcherror implementation though.

I'm OK with the Pretty instance.

**Comment by bartavelle** [comment]
Done in 92e370f

**Comment by PierreR** [comment]
I have just added an incomplete implementation:

https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter/Resolve.hs#L522

Unfortunately `catchError` does not seem to do anything useful. I have added a pending spec for that case.

I am also wondering what is the best option to handle multiple type arguments. Either I use `resolvePValueString` and change all `%x` into `%s` in the input string or I implement an `PrintfArg ` instance for `PValue`. What would you do ?

Then it should handle multiple args (but I leave that aside for the moment)

**Comment by PierreR** [comment]
I went for the first easier solution here: https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter/Resolve.hs#L521

I handle multiple args with this hack:
https://github.com/bartavelle/language-puppet/blob/master/Puppet/Utils.hs#L162

There is two mystery left:  the way I use `catchError` does not work (I am probably missing something obvious here) and it isn't working as expected for floating number (but really I don't care about that)

**Comment by bartavelle** [comment]
`catchError` does not work because it can't. Catching that `printf` error would only work with `Control.Exception.catch`, which requires `IO`. That means ditching the pure interpreter, which would be a shame ...

An alternative would be to refactor the interpreter to add an error handling function as a parameter, so that it would at least work in the IO case. It wouldn't work for the pure interpreter, and would make the code more clunky.

But the reason I like the free-monad pattern is that I can handle all the "dangerous" code in a single place, which make reasoning about the program easier. If we start adding exception-throwing code, it's all lost.

That's the reason I thought this was a large change :(

**Comment by bartavelle** [comment]
But I see you are using a hack to replace all `%.` with something else. This will not work properly, as stuff like `%3x` will fail! However this could be done in a much more cleaner way, without resorting to regexps and/or `Text.Printf`!

Just split the string on `%`, and handle the format arguments as they arrive?

**Comment by PierreR** [comment]
@bartavelle good idea, thanks ! I will try that later today or tomorrow.

**Comment by tbrouhier** [comment]
From my point of view, the tests are green. Thanks

**Comment by PierreR** [comment]
@bartavelle I have changed the implementation. Does it look right ?
I quite don't care about the two pending specs for now:
https://github.com/bartavelle/language-puppet/blob/master/tests/Function/SprintfSpec.hs#L43-L44

**Comment by PierreR** [comment]
@bartavelle I am surprised that the following floating conversion does not work:

```
> let Just s = text2Scientific "1.2"
> dummyEval (scientific2text <$> resolvePValueNumber (PNumber s))
Right "1"
```

**Comment by bartavelle** [comment]
I just commited a version that should be easier to extend. Let me know if I broke your use case.

**Comment by PierreR** [comment]
Nice. Thank you ! 

I have been using master for a while now. Would you mind releasing it as `1.3.7` ?

**Comment by bartavelle** [comment]
done
