### ISSUE TITLE
OS X Support

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#197]
We have recently got a new user that uses OSX.

Do you think it is possible to replace the `filecache` dependencies with something (like `vault` ?) that would work across both OSes ?

I could give it a try if you think it is not too much work (and with some guidance).

Thanks.

**Comment by PierreR** [comment]
I guess another option is to replace `hinotify` with something cross platform in `filecache`.

**Comment by bartavelle** [comment]
Using `hfsnotify` seems like a nice change. `vault` seems to be something else entirely.

**Comment by PierreR** [comment]
Does `language-puppet` re-use this `Data.FileCache` across invocation somehow ? 

Otherwise I don't quite see how the command benefits from `inotify`. I do undestand why a cache is necessary but the inotify feature of Data.FileCache does not seem to be useful in the `language-puppet` case.

**Comment by bartavelle** [comment]
For server implementations, it is useful :)

**Comment by PierreR** [comment]
Works now using FileCache 0.3
