### ISSUE TITLE
Add support for $facts hash [Puppet 4]

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#198]
This is a new feature in [Puppet4](https://docs.puppet.com/puppet/4.10/lang_facts_and_builtin_vars.html#the-factsfactname-hash) that is currently not supported in language-puppet.

**Comment by bartavelle** [comment]
That one isn't terribly hard, it might even already be implemented:

    type Facts = Container PValue

**Comment by PierreR** [comment]
Cool I will start giving this one a shot as soon as I can.

**Comment by PierreR** [comment]
To fix this, I can simply change [unifyFacts](https://github.com/bartavelle/language-puppet/blob/master/progs/PuppetResources.hs#L188-L189) with:
```
      unifyFacts :: Container PValue -> Container PValue -> Container PValue -> Container PValue
      unifyFacts defaults override c =
        let facts = override `HM.union` c `HM.union` defaults
        in HM.insert "facts" (PHash facts) facts
```
Does that sound right or should I tweak the facts params further down (for instance in IO.hs and Pure.hs) ?

**Comment by bartavelle** [comment]
why do you need to insert facts into facts?

**Comment by PierreR** [comment]
My understanding is that you should be able to retrieve facts with `$facts['os']['family']`  or just `$os.family` (or `$osfamily` with older versions of facter).
If I understand the spec correctly `$facts['key']` can't be override so this is a way to guarantee that you ask for data that won't be changed by the catalog. It replaces the unfortunate `$::osfamily` idiom (now deprecated at least as an idiomatic practice)

**Comment by PierreR** [comment]
It looks like a good change, making the distinction between facts and other variables explicit.

**Comment by bartavelle** [comment]
yes, looks good to me then!

**Comment by PierreR** [comment]
I have ended up doing it in `initialState` because I am also using `language-puppet` as a library.
