### ISSUE TITLE
Invalid resource file with source without file://

### ISSUE THREAD

**Issue by jfroche** [bartavelle/language-puppet#20]
when using a file resource with a source with file:/// we get the following  error:
<pre>
[svappcavl216.yaml] should have a source for /etc/puppet/puppet.conf
uncaught exception: IOException (user error (Could not find the file in [file:///tmp/_etc_puppet_puppet.conf/fragments.concat.out]))
</pre>

if we remove the file:/// from the source parameter in the file resource we get the following error:
<pre>
Invalid resource file {
  /etc/puppet/puppet.conf: # "./modules/concat/manifests/init.pp" (line 167, column 12) svappcavl216.yaml [Scope [Concat[/etc/puppet/puppet.conf]
                                                                                                                 ,class puppet::server
                                                                                                                 ,class profile::puppetmaster
                                                                                                                 ,class role::puppetmaster]]
    alias   => [concat_/etc/puppet/puppet.conf],
    backup  => puppet,
    ensure  => present,
    group   => root,
    mode    => 0644,
    owner   => root,
    path    => /etc/puppet/puppet.conf,
    replace => true,
    source  => /tmp/_etc_puppet_puppet.conf/fragments.concat.out;
}
A source should start with either puppet:// or file:// at # "./manifests/site.pp" (line 6, column 3)

</pre>

Puppet seems to accepts both notation in the source parameter http://docs.puppetlabs.com/references/latest/type.html#file-attribute-source. (also in tested in rspec in puppet sources)
Thanks for your help !

**Comment by PierreR** [comment]
Both "file://" and "/" are equivalent:
```
puppet apply -e "file {'$(pwd)/testme1.txt': ensure => present, source => 'file:///home/test/tmp/test'}"
puppet apply -e "file {'$(pwd)/testme2.txt': ensure => present, source => 'home/test/tmp/test'}"
```
