### ISSUE TITLE
Add support for `with` statement [Puppet 4]

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#200]
```
$tenfold = with( $input_number ) |$number| {
  $number * 10
}
```

**Comment by bartavelle** [comment]
What is that supposed to do ?

**Comment by PierreR** [comment]
https://docs.puppet.com/puppet/4.10/function.html#with

**Comment by bartavelle** [comment]
Oh my, this is a complicated feature again ...

**Comment by bartavelle** [comment]
I *think* I implemented `with` :)

**Comment by PierreR** [comment]
Cool.
It would be nice to support the case when the `with` statement is an expression:
```
  $fruit = with("apples", "oranges") |$x, $y| {
    "${x} and ${y}"
  }
```
```
ERROR: (swarm.manager.dev) This type of lambda function is not supported yet by language-puppet! with at ./modules/application/manifests/role/swarm/test.pp:4:3
```

**Comment by bartavelle** [comment]
Ah right.

**Comment by bartavelle** [comment]
It would be nice to rewrite it all though.

**Comment by bartavelle** [comment]
(currently "statements" and "expressions" are distinct things, which was the case before the "future parser")
