### ISSUE TITLE
Add support for double assignment [Puppet 4]

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#201]
```
$first = $last = 250
```

**Comment by bartavelle** [comment]
Argh, this is probably a non-trivial change!

**Comment by bartavelle** [comment]
This is an antifeature, what the hell are they thinking ?

**Comment by PierreR** [comment]
I know. Puppet is really bad at this. There are so many useless stuff you can do.

I don't mind not using such feature (I won't) but it is important to keep the parser happy if external puppetlabs modules do so.

So a quick workaround would do if such a thing exists :-)

**Comment by bartavelle** [comment]
This certainly won't be a quick workaround, at least for a robust solution ...

**Comment by bartavelle** [comment]
That could be the simplest task, but might break other parts of the parser. It could be done by:

 * changing the type of `varAssign` so that it returns a list of `VarAssignDecl`
 * altering the impacted code
 * surrounding the three first lines of `varAssign` into a `some`, and fixing the `return` statement
 * testing the shit out of this ...

**Comment by PierreR** [comment]
I knew this one would bite at some point:
https://github.com/puppetlabs/puppetlabs-kubernetes/blob/master/manifests/config.pp#L93

**Comment by PierreR** [comment]
Jeez I have just realized that the parser allows:
```
class test {
  String $test = "hello"
}
```
Which is not valid in Puppet

**Comment by PierreR** [comment]
Well I will have to give up ... It takes me too much time to fiddle with the parser.

@bartavelle Do you think you will be able to invest some time on it soonish ?

I don't believe I can fix all of these myself so if I know you won't I will probably go and search for another tool but if I know you will that would be cheerful news ;-)

**Comment by bartavelle** [comment]
I still want to rewrite the parser from scratch, so as to make it as close as possible to the puppet parser. I do not know how soon that will be though, I do not seem to find a lot of free time these days ...

Also, I had reports that they changed things with the facter, which is annoying. What are the alternatives though? Is there something usable for testing a catalog in puppet land?
