### ISSUE TITLE
Add support for hash and array literals [Puppet4]

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#202]
```
notify { "(['one','two','three'][1] )": } # produces the output "two"
```

**Comment by bartavelle** [comment]
Where is this feature described? It doesn't look useful at all at first glance.

**Comment by PierreR** [comment]
Would this be related to the fact that this is supposed to work in puppet:
```
puppet apply -e '$a = ["hello"]; notify {$a[0]:}'
```
but it won't parse with `puppetresources`.

From https://docs.puppet.com/puppet/5.0/function.html#each : 

```
$data = {"rtr" => "Router", "svr" => "Server", "wks" => "Workstation"}
$data.each |$items| {
 notify { $items[0]:
   message => $items[1]
 }
}
```

**Comment by bartavelle** [comment]
That is quite different from the first message, where for some reason the inner part of a string should be "eval'ed". That looks saner.

**Comment by bartavelle** [comment]
I just pushed something that uses the full expression parser for resource names. It might break everything though.
