### ISSUE TITLE
Empty strings in boolean context are true [Puppet 4]

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#205]
```
  if '' {
    notify {"empty string is true":} # Pupppet 4
  } else {
    notify {"empty string is false":} # language-puppet 
  }
```
https://docs.puppet.com/upgrade/updating_manifests.html#empty-strings-in-boolean-context-are-true

Looks like an insane change to me ...

**Comment by bartavelle** [comment]
aaaaaaaaargh

**Comment by bartavelle** [comment]
Or perhaps, something that would be more reasonable given the amount of effort I can put in this project, not offer support for puppet 4 ...

**Comment by PierreR** [comment]
Well `puppet 3` is already unsupported so if the project does not offer `puppet 4` support, it will die quickly.

We are planning to migrate to `puppet 4` by the end of the year (Q4), unless we decide to go on with `puppet 3` for a while and replace `puppet` altogether (but that's unlikely).

I am willing to help myself but if the project doesn't support `puppet 4`, I will have to find an alternative.

It is really up to you of course.  The soon I know about it, the better ;-)

**Comment by PierreR** [comment]
As a more cheerful comment, I have heard that the language changes were kept to a minimum in Puppet 5 ;-)

**Comment by bartavelle** [comment]
I will keep on supporting the project in the foreseeable future, but this will be low effort. If you want to work on the code more, there will be no problem supporting puppet 4!

**Comment by PierreR** [comment]
Let's try and go for it then. I guess the best is to first focus on issues that will work in both `puppet3` and `puppet4`. And then create a separate branch for puppet4 and release it as `language-puppet-1.4` or something.

I believe I have caught most of the migration issues at this point. It would be nice to create a github label `puppet4` for issues such as this one where the code needs to diverge.

**Comment by bartavelle** [comment]
Why not a command line flag ?

**Comment by PierreR** [comment]
Sure. I guess I can actually introduce the flag and solve this issue. It is probably not so hard, isn't ?

**Comment by PierreR** [comment]
Closing with 1b9ebe2.
The flag is not implemented as it makes less and less sense to support puppet 3 (see #240)
