### ISSUE TITLE
Support data type syntax [Puppet 4]

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#206]
From https://docs.puppet.com/puppet/latest/lang_data_type.html#parameter-lists
```
class ntp (
  Boolean $service_manage = true,
  Boolean $autoupdate     = false,
  String  $package_ensure = 'present',
  # ...
) {
  # ...
}
```

**Comment by bartavelle** [comment]
I added support for the define/class declaration syntax, and the selector syntax. At least the `case` syntax is missing, but it would be awesome if you could test it!

**Comment by PierreR** [comment]
I have been using the master version for a while without problem. I am still using the `puppet4` syntax scarcely but I would suggest to make a new release with the current changes (so I can more easily test it with more catalogs).

As an aside, the point that worries me the most for the moment is the `dot` alternative syntax for lambda and cie (`$binaries.each |String $binary| {`). I guess I should fill in a new issue about that.

**Comment by bartavelle** [comment]
Ah, that might not be too much trouble to add.

**Comment by bartavelle** [comment]
Uploaded 1.3.8

**Comment by bartavelle** [comment]
I just pushed datatype syntax support in lambda expressions.

**Comment by PierreR** [comment]
Isn't this supposed to work ?
```
$xs =  ["hello", "world"]
each($xs) |String $x| {
}
```
I was trying it but got:
```
unexpected '|'
expecting '}', Statement, or rest of Statement
```
