### ISSUE TITLE
Implement the `lookup` function

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#207]
The `lookup` function replaces `hiera`, `hiera_array` and `hiera_hash` function: 
https://docs.puppet.com/puppet/4.10/hiera_use_function.html

**Comment by PierreR** [comment]
The function `lookup` also works in puppet 3 (tested with 3.8.7).

**Comment by bartavelle** [comment]
Is that me or did they introduce special syntax for the lambda form?

**Comment by bartavelle** [comment]
Or is their function returning yet another internal new type that can be a hash when used in this context, and is merged in other contexts ?

**Comment by bartavelle** [comment]
Oh no, it is even more complicated! I am not sure how to handle that.

**Comment by PierreR** [comment]
This is done. Hash argument are not yet supported but I will add this when the need occurs.
