### ISSUE TITLE
Implement stdlib sort.

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#211]
I am giving this a try and I am left wondering how to achieve : 

```
let a = PArray (V.fromList [PString "world", PBoolean True, PString "hello"])
a ^. _PArray.traverse._PString 
-- gives "helloworld" how can I get ["hello", "world"] so I can do List.sort on it ?
```
I guess there is something simple that I don't see yet ;-) 

Any hint would be welcomed.

**Comment by PierreR** [comment]
I guess in practice I should really throw an exception when the array is not all PString or all PNumber

**Comment by PierreR** [comment]
I came up with this so far:
```
sort :: PValue -> InterpreterMonad PValue
sort (PArray s) = do
  let toText (PString v) = return v
      toText _ = throwPosError ("sort(): the current implementation only sort a list of strings")
  v <- mapM toText (V.toList s)
  return $ PArray (V.fromList (map PString (List.sort v)))
sort x = throwPosError ("sort(): Expect to sort an array, not" <+> pretty x)
```
Is there a way to make this a bit idiomatic ?

**Comment by bartavelle** [comment]
Answering quickly from the phone. ^. Is view. It returns a single value,
which is a monoidal summary in case of things that are not lenses
(traversal). You need tolistof, or ^.. Here.

**Comment by PierreR** [comment]
Do you see a way to make the current implementation working for both array of string and ints ? I am quite curious about this.

**Comment by bartavelle** [comment]
I have a few minutes with a computer, so:

 * `toText` already exists (`resolvePValueString`)!
 * what is the requirement when sorting an array with heterogeneous values ?

**Comment by PierreR** [comment]
To mimic the ruby implementation, array with heteregenous value should fail. In ruby, array with boolean values also fails.

I knew about `resolvePValueString` but didn't use it because it might not do what is expected with array of boolean values or integer values. 

Out of curiosity I would love to see an implementation that only sort array of ints and array of strings. I am wondering how to handle the fact that we need to go from PValue to String and Int, sort such array and then back to the previous type.

**Comment by bartavelle** [comment]
Just pushed an example with code  duplication

**Comment by PierreR** [comment]
Thanks !

**Comment by bartavelle** [comment]
Factorized the code, in case you want to see the kind of things you can do with prisms.
