### ISSUE TITLE
Travis failure

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#212]
Travis seems to fail because of the SafeProcess module.

I think this module is not used. Shall we remove it ?

**Comment by bartavelle** [comment]
Well, it will be made pretty obvious if that module is not used :) Why not try?

**Comment by PierreR** [comment]
Build is passing again but I had to remove ghc-7.10 (which I guess is not a big deal) and remove `haddock` generation for ghc-8.2.1.

I really don't know why it [blocks](https://travis-ci.org/bartavelle/language-puppet/jobs/263296956). I am still using `ghc-8.0.2` so I could not witness this locally. 

For the record, there are some strange warnings with `ghc-8.2.1` (they don't seem to make sense) about:
```
<no location info>: warning: [-Wmissing-home-modules]

    These modules are needed for compilation but not listed in your .cabal file's other-modules: Paths_language_puppet
```
