### ISSUE TITLE
Support DataType in puppet function (Resolve.hs)

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#223]
Some puppet function can now take a type as its argument. For instance:
```
lookup('classes', Array[String], 'unique')
```

Currently `resolveFunction` accepts Expression only.

Would you mind helping with this ? Either with code or by outlining  the solution ?

Thanks

**Comment by bartavelle** [comment]
A `PValue` can be a `DataType`, but an `UnresolvedValue` can't. A case should be added in this type, and the `terminalG` function should be extended to parse types. This *looks* straightforward, but it might break parsing in unforeseen ways :)

**Comment by bartavelle** [comment]
One you add a `DataType` case in `UnresolvedValue`, warnings should appear in several places. Fix them mechanically, and this should be good.

**Comment by PierreR** [comment]
I have had a try in https://github.com/bartavelle/language-puppet/pull/222 but the added tests for lookup with a datatype are still failing (see pending tests).

I guess what I have (blindly) done in the `terminalG` function is not correct ?

https://github.com/bartavelle/language-puppet/pull/222/commits/4bfb48faf7eb4d54f4343e120f53317557fff1be

**Comment by bartavelle** [comment]
Looks like I would have done. You get parse errors?

**Comment by bartavelle** [comment]
You need to put it above ResourceReference, and hope nobody used a resource reference with the same name as a type ...

**Comment by PierreR** [comment]
I have tried this already but it did not make any difference. I have just pushed the change now (the pending is still failing).

**Comment by PierreR** [comment]
If I change the test for `    it "should succeed with two arguments, the second on being a datatype" (checkSuccess ["hostname", Terminal (UDataType (DTString Nothing Nothing))] "pure")` it works.

So probably something missing with the `IsString` instance ?

**Comment by PierreR** [comment]
Works fine outside the test ... So there is no need to change any "IsString" instance ...

**Comment by PierreR** [comment]
Is it expected to use the whole `Terminal (UDataType (DTString Nothing Nothing)` in that context ? The problem might come from a partial `IsString` implementation for Expression, is that so ?

**Comment by bartavelle** [comment]
It should not be partial! It should translate any string to the corresponding unresolved string. Where is the failing test?

**Comment by PierreR** [comment]
The test is here: https://github.com/bartavelle/language-puppet/blob/master/tests/Function/LookupSpec.hs#L21
If I replace `Terminal (UDataType (DTString Nothing Nothing)` by 'String' the test is failing.

**Comment by bartavelle** [comment]
It would mean the following puppet code:

    lookup("hostname", "String")

Which I suppose should fail with puppet too?

**Comment by PierreR** [comment]
Ah you are right. It should be `lookup ("hostname", String)`. 

So I guess the way the test is currently written is correct.
