### ISSUE TITLE
New release in hackage

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#225]
Would you mind releasing master maybe as `1.4.0` to mark the new (partial) puppet 4 support ?

I still need to fix some missing parts on the lookup function but I can do that along `1.4.0`.

Then I might have a try with #216 because many puppetlabs modules start failing because of this one.

My motivation is to have a version bump for the next LTS (it looks like nightly will be the next LTS-10 quite soon now). I then get some caching for free from nixos (which only build upon lts)

Thanks

**Comment by bartavelle** [comment]
Note that supporting custom types will actually by quite painful, as differentiating types from resource references will need to be made during parsing, or the parser will need to be altered significantly.

**Comment by PierreR** [comment]
Unless you have a quick fix for #213 I would go for a new release. Everything works with my set of puppetlabs modules updated to their last version. I expect the 3 remaining `P2` issues to be blocking at some point. I can just change them into `P1` when it happens.

**Comment by bartavelle** [comment]
It is up, but I skimmed over your first comment and did not update to 1.4 ....

**Comment by PierreR** [comment]
Never mind about 1.4. Thanks ;-)

**Comment by PierreR** [comment]
And as a bonus you manage to release 1.13 the 13 of December ;-)
