### ISSUE TITLE
Datatype parsing error in puppetlabs-postgresql

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#227]
The parser is failing on [this line ](https://github.com/puppetlabs/puppetlabs-postgresql/blob/5.2.1/manifests/server/grant.pp#L73).

with:
```
x puppet.foreman.dev: ./modules/postgresql/manifests/server/grant.pp:73:9:
unexpected 'P'
expecting '}'
 at # SourcePos {sourceName = "./modules/postgresql/manifests/server/database_grant.pp", sourceLine = Pos 10, sourceColumn = Pos 31}
```

I guess this is such a case ...

**Comment by PierreR** [comment]
PS: the parser will also fail before that error in [this line](https://github.com/puppetlabs/puppetlabs-postgresql/blob/5.2.1/manifests/server/pg_hba_rule.pp#L50)

**Comment by bartavelle** [comment]
Now there can be arbitrary expressions in data type declarations? How nice :(

**Comment by PierreR** [comment]
For the second error, I can easily fork the module and remove the `assert_type` line. The first one looks more like a bug.

**Comment by bartavelle** [comment]
Ideally both should be supported.

**Comment by bartavelle** [comment]
The `Pattern` failure is yet another puppet-ism :( According [to the docs](https://puppet.com/docs/puppet/5.3/lang_data_abstract.html#pattern) there should be a list of regular expressions, but apparently this is accepted :/

**Comment by bartavelle** [comment]
They do the right thing at line 5 anyway. This is really annoying.

**Comment by bartavelle** [comment]
I just pushed a dirty fix, that I did not test. Hopefully it will work.

**Comment by PierreR** [comment]
It is working nicely so far. Thanks
