### ISSUE TITLE
Variables without `@` are incorrectly resolved in erb file

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#237]
In a pp file:
```
class test (
$bar = 'hello',
) {

  file {
    '/etc/foo':
      ensure  => present,
      content => template('mymodule/test.erb'),
  } 

}
```
In a erb template:
```
foo: <%= bar %>
```

Using `puppetresource -p . -o test -t file --showcontent` this would incorrectly show the value of bar instead of complaining because there is a missing `@` in front of bar in the erb file.

**Comment by bartavelle** [comment]
Well, in previous version this worked fine, so removing this (and I do not really know how :) would break all that code!

**Comment by bartavelle** [comment]
I know I have seen a ton of warning on the puppet servers about other people modules and the lack of `@`. Perhaps it is all fixed these days ...

**Comment by PierreR** [comment]
FWIW, in puppet 4, when `@`  is missing, puppet exits with a rather nice and explicit error.

I am primary using `language-puppet` to avoid runtime puppet errors. It is so much nicer to get the error upfront instead of down the line ;-)

**Comment by bartavelle** [comment]
Alright, if it crashes on puppet 4, then this should be deprecated.

**Comment by bartavelle** [comment]
I should move to puppet 4 in the next weeks. I suppose I will find all kind of stuff like that :/

**Comment by PierreR** [comment]
#213 should be fixed before. It describes a bug that is not related to puppet4.

**Comment by PierreR** [comment]
Is 35e89eaa62ead1487 alright by you ?

If it is, I will close the issue.

**Comment by bartavelle** [comment]
I will release a new version.
