### ISSUE TITLE
Consolidate all tests into one cabal test-suite

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#238]
I will shortly commit a change that starts doing this.  I have been bitten a couple of times by a green test line not realizing it was failing at the top scrolling part of the terminal.

I am creating this issue to discuss these changes along.

**Comment by bartavelle** [comment]
Yeah, that certainly would make it integrate better with things like "stack test".

**Comment by PierreR** [comment]
About `test-suite erbparser` it does not seem to do anything at least when it is run with `stack test` ? Shall we keep it after adding some inputs or shall we remove it ?

**Comment by PierreR** [comment]
First pass with 4a0dec1

**Comment by bartavelle** [comment]
When the args are null it should probably try parsing some test erb, yes.
