### ISSUE TITLE
Drop Puppet 3 support

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#240]
With the latest versions of the `concat` submodule, the `ensure` attribute is forbidden on the `fragment` resource:

https://github.com/puppetlabs/puppetlabs-concat/blob/master/lib/puppet/type/concat_fragment.rb

To support this we need to remove this line:
https://github.com/bartavelle/language-puppet/blob/master/src/Puppet/Language/NativeTypes/Concat.hs#L40

This change would completely break a puppet 3 compatible version that requires an older version of the `concat` module.

Maybe it is time to create a release `1.4.x` that would stop supporting puppet version < 4 ?

What do you think ?

**Comment by bartavelle** [comment]
Sounds good to me. However it will probably require a bit more work before
release.
