### ISSUE TITLE
Add Regexp data type

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#248]
Parsing of a regex type is failing:

```
class application::test (
  Regexp $foo = /test/
) {
}
```

https://puppet.com/docs/puppet/5.3/lang_data_regexp.html#the-regexp-data-type

**Comment by bartavelle** [comment]
Does that patch even work ? :)

**Comment by PierreR** [comment]
It looks like I sitll get the message : 
```
Regular expressions are not allowed in this context:  /test/
```

**Comment by PierreR** [comment]
I believe I fix this ;-)

**Comment by bartavelle** [comment]
yay!
