### ISSUE TITLE
Functions from the docker module

### ISSUE THREAD

**Issue by jfroche** [bartavelle/language-puppet#252]
Hello,

We would like to validate puppet code that make use of the puppetlabs/docker module.
Here are some of the functions used in the module:

 - pw_hash (https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/lib/puppet/parser/functions/pw_hash.rb)
 - docker_swarm_join_flags (https://github.com/puppetlabs/puppetlabs-docker/blob/master/lib/puppet/parser/functions/docker_swarm_join_flags.rb)

Thank you for your help !

**Comment by PierreR** [comment]
´pw_hash´ is already mocked. Do you need the a concrete implementation ?
https://github.com/bartavelle/language-puppet/commit/796119fdbcf13864dc0fe891bd501e263c8303f6

**Comment by jfroche** [comment]
No, indeed wasn't using that version. Tkx

**Comment by PierreR** [comment]
Very simple mock implemented in bfc980c63ae89aef5793ca60253c89b68e6a04d9
