### ISSUE TITLE
Cannot parse assert_type lambda

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#253]
I guess this is similar to #200.

Would it be possible to support the following idiom:

```
 assert_type(Pattern[/^(aufs|devicemapper|btrfs|overlay|overlay2|vfs|zfs)$/], $storage_driver) |$a, $b| {
...
}
```
It is used for instance in https://github.com/puppetlabs/puppetlabs-docker/blob/master/manifests/init.pp#L529

It is currently failing to parse with:
```
x swarm.worker.testing: cannot parse ./modules/docker/manifests/init.pp:492:68:
    |
492 |     assert_type(Pattern[/^(Debian|RedHat|windows)$/], $::osfamily) |$a, $b| {
    |                                                                    ^
unexpected '|'
expecting '}' or Statement
 at ./modules/profile/manifests/docker.pp:116:5

```

**Comment by bartavelle** [comment]
It is indeed similar to #200.

**Comment by bartavelle** [comment]
It is possible to support such functions in an ad-hoc way, but it would be nice to have a principled way.

**Comment by bartavelle** [comment]
(Please tell me this is the case)

**Comment by PierreR** [comment]
Unless I am missing something, I have the same error:
```
x swarm.worker.testing: cannot parse ./modules/docker/manifests/init.pp:491:68:
    |
491 |     assert_type(Pattern[/^(Debian|RedHat|windows)$/], $::osfamily) |$a, $b| {
    |                                                                    ^
unexpected '|'
expecting '}' or Statement
```

**Comment by PierreR** [comment]
ouch that's wicked. The lexer spec tests are not running on travis for some reason.

When I do a `cabal test` these tests are failing ...

**Comment by bartavelle** [comment]
I think that if you remove the type as the first argument, you would have another parsing error. This is yet another parsing problem. I think it would be nice to have a formal grammar for the language, but this will probably not happen ...

**Comment by PierreR** [comment]
I am not so sure because this is failing the same way and there is not type annotation:
```
class application::role::swarm::test (
) {
  $fruit = with("apples", "oranges", "bananas") |$x, $y, $z| {
    "${x}, ${y}, and ${z}"
  }
  notify {"${fruit}":}
}
```
```
ERROR: (swarm.manager.dev) cannot parse ./modules/application/manifests/role/swarm/test.pp:3:49:
  |
3 |   $fruit = with("apples", "oranges", "bananas") |$x, $y, $z| {
  |                                                 ^
unexpected '|'
expecting "!=", "!~", "<<", "<=", "==", "=~", ">=", ">>", "and", "in", "or", '*', '+', '-', '.', '/', '<', '>', '[', '}', or Statement
 at ./modules/application/manifests/role/swarm/manager.pp:2:3
```

**Comment by bartavelle** [comment]
right, this is getting problematic :) I think it is time to rewrite the parser from scratch, using something like happy

**Comment by PierreR** [comment]
This is well above my head but I would be quite interested to know more precisely why `megaparsec` isn't a good fit anymore (as I find parser quite fascinating in general) ;-)

**Comment by bartavelle** [comment]
But in theory `megaparsec` does the job just fine!

**Comment by PierreR** [comment]
So the plan would be the rewrite the parser with `megaparsec` with the help of something like `happy` to understand the interaction more.

**Comment by bartavelle** [comment]
I don't know at all. The plan right now would be to find some description of the language, so that I am not chasing randomly using only examples.

**Comment by PierreR** [comment]
[This ]( https://github.com/puppetlabs/puppet-specifications/tree/master/language) might be helpful ?

**Comment by PierreR** [comment]
I suspect the problem comes from the `lambdaCall` parser particularly the line that parses the with argument (list of expression separated by a comma) ?
https://github.com/bartavelle/language-puppet/blob/master/src/Puppet/Parser.hs
What do you think ?

**Comment by PierreR** [comment]
Maybe  `hoLambdaExpr`   should be `Vector Expression` ?

**Comment by PierreR** [comment]
https://github.com/puppetlabs/puppet-specifications/blob/4e54d7a8c1e8f16c1cdbc44d4b5537c27784e7cd/language/calls.md#arguments

**Comment by bartavelle** [comment]
It is very helpful!

**Comment by bartavelle** [comment]
Oh right, that is the problem!

**Comment by bartavelle** [comment]
Do you want to try fixing this?

**Comment by PierreR** [comment]
No really ;-) I have had a go fixing the parser but then there is still many bits to change in resolve and I am not sure I know fully what I am doing. But if you don't have the time, I can give it a proper try if you prefer.

**Comment by PierreR** [comment]
It works !
