### ISSUE TITLE
Cannot parse boolean condition on type

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#255]
Something that probably should be supported ?

```

  if (Integer($::operatingsystemmajrelease) < 7){
    ...
  }

```

```
x swarm.worker.testing: cannot parse ./modules/docker/manifests/init.pp:492:51:
    |
492 |   if ($::operatingsystem == 'CentOS') and (Integer($::operatingsystemmajrelease) < 7){
    |                                                   ^
unexpected '('
expecting "!=", "!~", "<<", "<=", "==", "=~", ">=", ">>", "and", "in", "or", ')', '*', '+', '-', '.', '/', '<', '>', or '['

```

**Comment by bartavelle** [comment]
Amusing :(

**Comment by bartavelle** [comment]
I tried switching the parsing order between functions and datatypes, does that help?

**Comment by PierreR** [comment]
I initially thought this was a mere check but it is actually a cast ... So it seems from the tests of [this PR](https://github.com/puppetlabs/puppetlabs-docker/pull/330) seems to prove. This language is so ... surprising.

**Comment by bartavelle** [comment]
What does that mean in the first place? Datatypes can be called like functions and this results in a cast sometimes? Or is that just `Integer`?

**Comment by PierreR** [comment]
I have found this info in the spec: 
https://github.com/puppetlabs/puppet-specifications/blob/3c0f46adf68000c08dcb04fa4a61e73560a6787b/language/types_values_variables.md#integernew

**Comment by bartavelle** [comment]
beuh :(

**Comment by bartavelle** [comment]
Do you mind checking if my last commit breaks stuff?

**Comment by PierreR** [comment]
Tested against a couple of nodes and it works without issues.

Thanks.
