### ISSUE TITLE
Optional value should be set to Nothing when value '~' is set in Hiera

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#261]
If you define such a class:
```
class application::docker::elastic (
  Optional[String] $version
) {

}
```
With a key/value set to `application::docker::elastic::version: ~` in hiera, language-puppet should not complain about a mandatory parameter not set : 
```
ERROR: (docker.elastic.dev) The following mandatory parameters were not set: (version) when including class application::docker::elastic at ./manifests/site.pp:14:5
```

**Comment by bartavelle** [comment]
I do not know what `~` means!

**Comment by PierreR** [comment]
It means 'NULL' in yaml: https://stackoverflow.com/questions/8667766/what-does-mean-in-the-yml-configuration-file-in-symfony-2

**Comment by PierreR** [comment]
The Yaml parsing bit seems to work quite alright: https://github.com/bartavelle/language-puppet/commit/12aa29b4d2c7cde376931415c2582eb05a500454
