### ISSUE TITLE
Parsing fails with expression in selector

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#262]
Puppet doc: https://puppet.com/docs/puppet/5.3/lang_conditional.html#location

From https://github.com/pcfens/puppet-filebeat/blob/master/manifests/params.pp#L55
```
puppetresources --parse ./modules/filebeat/manifests/params.pp
ERROR: cannot parse ./modules/filebeat/manifests/params.pp:55:64:
   |
55 |       $major_version = versioncmp('6.3', $::kernelversion) < 0 ? {
   |                                                                ^
unexpected '?'
expecting "<=", ">=", '<', '>', '}', Statement, operator, or the rest of Statement
```

To fix it, you'd need to wrap with parens:  `$major_version = (versioncmp('6.3', $::kernelversion) < 0) ? {`

**Comment by bartavelle** [comment]
Does that help?

**Comment by PierreR** [comment]
Yep, seems to work nicely. Thanks !
