### ISSUE TITLE
Add `validate_cmd` option for concat ressource

### ISSUE THREAD

**Issue by jfroche** [bartavelle/language-puppet#265]
We are missing the `validate_cmd` which can be provided to the concat resource (see
https://github.com/puppetlabs/puppetlabs-concat/blob/master/manifests/init.pp#L71).
It is a string, my guess would be to add the option in https://github.com/bartavelle/language-puppet/blob/master/src/Puppet/Language/NativeTypes/Concat.hs#L15

Thank you !

**Comment by PierreR** [comment]
Fix with 973abd7
