### ISSUE TITLE
Make test failing with unknown function

### ISSUE THREAD

**Issue by gevraud** [bartavelle/language-puppet#266]
Issue with haproxy module

Error : 

→ make test
Make test
✓ nginx.dev
x haproxy_dev: Unknown function: dirname at ./modules/haproxy/manifests/resolver.pp:105:3

The build has failed with 1 failures!
Error when running Shake build system:
* test
ExitFailure 1

function is present on line 105 :    validate_absolute_path(dirname($_config_file))

**Comment by PierreR** [comment]
The missing function is here:
https://github.com/bartavelle/language-puppet/blob/master/src/Puppet/Runner/Stdlib.hs#L48
Spec here: https://forge.puppet.com/puppetlabs/stdlib#dirname

**Comment by PierreR** [comment]
Will do it asap
