### ISSUE TITLE
File resource with recursion cannot find files.

### ISSUE THREAD

**Issue by ppomes** [bartavelle/language-puppet#272]
Hi,

Here is a tgz showing a regression with recurse=>true on a File resource. This code is working with puppetresources 1.3.14 (the previous version I was using).

With 1.4.3:
```
ppomes@haskell ~/testpp adm>: /usr/bin/puppetresources -p . -a allnodes

ERROR: (node1) : Could not find [puppet:///modules/testpp/dir]
                 searched in './modules/testpp/files/dir'
```

[testpp.tar.gz](https://github.com/bartavelle/language-puppet/files/2958768/testpp.tar.gz)

**Comment by ppomes** [comment]
![image](https://user-images.githubusercontent.com/787238/54236501-0812da00-44ea-11e9-8f4f-9780e7a3af4a.png)

stat is done on the right directory

**Comment by bartavelle** [comment]
Right, the code uses `doesFileExists`, but should also check `doesDirectoryExists` when `recurse` is set to `True`.

Sidenote for when I will be back home to fix this (or if someone checks it first, *wink wink*), `checkAllSources` would be more elegant if it used the `Validation` applicative instead of manually  concatenating the failures.

**Comment by PierreR** [comment]
@bartavelle I have to admit I don't see how to use Validation within IO (yet).

**Comment by PierreR** [comment]
@ppomes In case you need a workaround while waiting for the fix you can set `extratests` to false:
https://github.com/bartavelle/language-puppet/blob/master/tests/defaults.yaml#L49

**Comment by bartavelle** [comment]
Does master solve the issue?

**Comment by ppomes** [comment]
Yes!! thanks, issue can be closed.

**Comment by PierreR** [comment]
@bartavelle no regression on my side but I quite don't understand the last commit: 1719af114f64beca8fe8563da9b29a99556a5143. Isn't "source" where the filepath would be ?

**Comment by ppomes** [comment]
@PierreR @bartavelle: Well, I also have the same question!

**Comment by PierreR** [comment]
@bartavelle actually I am pretty sure there is a regression. Now the tests always pass even when the source of a path is wrong ...

**Comment by PierreR** [comment]
I can confirm that the latest commit 1719af1 is causing the regression. I have the feeling that after this commit the test is not effective anymore.

**Comment by bartavelle** [comment]
Oh that is a brainfart over another brainfart. Lemme check this.

**Comment by bartavelle** [comment]
Also, `Validation` exists but not `ValidationT` contrary to what I thought!
