### ISSUE TITLE
Hiera lookup fonction not working with integer

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#274]
If zookeeper:client_ip is an integer, such call `zookeeper.connect: "%{lookup('zookeeper::client_ip')}:%{lookup('zookeeper::client_port')}"` in a hiera file will resolve as:
```
zookeeper.connect=127.0.0.1:
``` 
If I add some quote where the variable `zookeeper::client_port` is defined I will get the right output. (unfortunately I can't do so as it will result in a type missmatch error in puppet code).

**Comment by bartavelle** [comment]
Also pushed something for this issue, let me know if it helps

**Comment by PierreR** [comment]
Works nicely. Thanks.
