### ISSUE TITLE
Error in reduce

### ISSUE THREAD

**Issue by jfroche** [bartavelle/language-puppet#276]
Hello !
The following expression fails:

```
$i = ['a', 'b'].reduce({}) |$result, $k| {
  merge($result, {"key.${k}" => $k})
}
```
with the following error message:
```
You can't combine chains of higher order functions (with .) and giving them parameters
```

I see [here](https://github.com/bartavelle/language-puppet/blob/6f72ac9b06e8e0016be1f654ca94c65269265886/src/Puppet/Interpreter/Resolve.hs#L805) that the reduce is not implemented yet, would it be hard to implement it ?

Thank you !

**Comment by bartavelle** [comment]
I just pushed a completely untested implementation of the reduce function.

**Comment by PierreR** [comment]
LGTM
