### ISSUE TITLE
Hiera hash are not merged between layers

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#277]
Given such a call to a hash named 'users' in a pp file `$users = lookup('users', Hash, hash, {})`, the hash will not be merged across [hiera layers.](https://puppet.com/docs/puppet/4.10/hiera_layers.html)

Within the same layer, the merge is working but between layers the merge will not happen.

**Comment by bartavelle** [comment]
Can you build me a minimal archive that demonstrates the problem? This looks like quite a bit of work to fix at first glance :/

**Comment by PierreR** [comment]
[Here](https://github.com/bartavelle/language-puppet/files/3197755/277.tar.gz) is a minimal case.

I guess the problem is here:
https://github.com/bartavelle/language-puppet/blob/master/src/Puppet/Interpreter/IO.hs#L105

We don't merge any values across layers in that function.

**Comment by PierreR** [comment]
Thinking about this a bit more, I wonder if there is a (immediate) need to merge from the module layer (because each key needs to be prefix by the module name).

As a first step we would just merge hashes from the global and the environment layers.

**Comment by bartavelle** [comment]
I will try to take a good look at this during the weekend.

**Comment by PierreR** [comment]
Thanks.

Forget about my previous comment ...

We do need to merge hashes across all layers. That said the most important is probably to merge hashes from the module layer and the environment layer. 

[Here](https://github.com/bartavelle/language-puppet/files/3213125/277.tar.gz) is a new test case that is more representative.

**Comment by bartavelle** [comment]
I reworked the hiera part a bit, does that work better?

**Comment by bartavelle** [comment]
(just fixed the previous commit)

**Comment by PierreR** [comment]
Seems to work nicely so far.

Thanks !
