### ISSUE TITLE
Update to Aeson 2.x.x

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#292]
It is getting harder to compile language-puppet with aeson 1.x.x with newer version of ghc. Newer version of hruby are also using aeson 2.x.x, same for servant, ...

Would it be possible to update aeson to 2.x.x for language-puppet.

This is the kind of error I have and I don't really see how to fix it:

```
src/XPrelude/Extra.hs:158:22: error:
    • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
                     with: HashMap Text Value
      Expected: HashMap Text Value
        Actual: aeson-2.0.3.0:Data.Aeson.Types.Internal.Object
    • In the third argument of ‘HM.alterF’, namely ‘o’
      In the second argument of ‘fmap’, namely
        ‘(HM.alterF (traverse f) k o)’
      In the expression: fmap Object (HM.alterF (traverse f) k o)
    |
158 |         fmap Object (HM.alterF (traverse f) k o)
```

Thanks.

**Comment by PierreR** [comment]
For some reasons, I can't build hruby 0.3 anymore. Would love to update to 0.4 (not 0.5 because I can't build it either).

**Comment by bartavelle** [comment]
I updated the dependencies!
