### ISSUE TITLE
regsubst function failure when the second param is a Pattern

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#295]
The following signature doesn't seem to be supported in language-puppet:

```
regsubst($ipaddress, /([0-9]+)/, '')
```

It is used here in the systemd module: https://github.com/voxpupuli/puppet-systemd/blob/master/manifests/dropin_file.pp#L88

I have this error:

```
Don't know how to convert this to a string:
/\.service$/ at ./modules/systemd/manifests/dropin_file.pp:88:7
```

**Comment by bartavelle** [comment]
pushed a fix
