### ISSUE TITLE
Purpose of Testing.hs

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#87]
It looks to me that `Testing` currently contains a lot of code just to test 2 properties :

* When a resource is a file it checks if the file exists.
* It checks that all users and groups referenced by cron, file, etc. types are defined somewhere in the catalog

For the first point, is it because it needs IO that it cannot be done in the Native type ? That would be rather unfortunate as it forces us to maintain 2 different test locations (note that the test here is a duplicate:  https://github.com/bartavelle/language-puppet/blob/master/Puppet/NativeTypes/File.hs#L54)

Then there is a lot of dead code in `Testing.hs`. Most of the exposed functions are used nowhere outside and could even be completely removed.

I am just asking because I have made another attempt to upgrade `hspec` and reliazed that the way we use it is probably not supported anymore. See https://github.com/hspec/hspec/issues/215

**Comment by bartavelle** [comment]
That's not the actual point of this module. I used it to write unit tests on my catalogs, and compiled it as a standalone program. A bit like using `puppetresources` with pre-defined options and additional tests on the continuous integration server.

I wanted to add more properties and write a post about using this, but I guess we can scrap it now.

**Comment by PierreR** [comment]
Do you want me to scrap it ?

Where should I put/kept the two tests (file source check and usergroupdefined) ?

**Comment by bartavelle** [comment]
Oh you probably can just scrap it, I never was satisfied with this approach, and this will just be another lump of dead code that will need maintaining ... thanks for that !

**Comment by PierreR** [comment]
While I am at it, do you want to keep `--allnodes` and `--deadcode` ?

The fact that it works only when nodes are declared in `site.pp` (regex are not supported IIRC) looks a bit adhoc. I don't use this myself because I don't manage my nodes in `site.pp`. The mapping is done using facts dynamically.

**Comment by bartavelle** [comment]
I do believe those are useful features ...

**Comment by PierreR** [comment]
Ok. I might try to make `allnodes`  works with a set of nodes passed as arguments (and default to allnodes otherwise) ?

**Comment by bartavelle** [comment]
oh that would be nice !

**Comment by PierreR** [comment]
Oups what a garbage here ...

I meant to submit a pull request for this heavy change ... but somehow my remote seems a bit off ...

Could you let me know if the last commit is OK by you ? Let me know if you want me to change anything.

**Comment by PierreR** [comment]
I also wonder if it is possible to do something cleaner here:
https://github.com/bartavelle/language-puppet/blob/master/progs/PuppetResources.hs#L281

**Comment by bartavelle** [comment]
Do you know the saying "give me a 5 lines code review and I'll find 10 defects, give me a 500 lines and I'll tell you everything is fine". Everything seems fine ;)

What do you mean by cleaner ? The repetition ?

**Comment by PierreR** [comment]
Yep it looks a bit strange to do twice the mapping (once with `catMaybes` and the other one with `map`).

**Comment by bartavelle** [comment]
It would be nicer if there was some sort of `parMapM` function ...
