### ISSUE TITLE
[New Release] Does not run on Debian wheezy or Ubuntu 14.04

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#88]
I looks like a real bug from `hruby` to me. See https://github.com/bartavelle/hruby/issues/7

In case it won't be fixed (most distros are using Ruby 2 nowadays even CentOS 7) we might want to update the doc to make it clear it won't work on this platform ?

**Comment by bartavelle** [comment]
What's the ruby version they are using ?

**Comment by PierreR** [comment]
Both debian wheezy and ubuntu 14.04 are using ruby 1.9.3:

https://packages.debian.org/search?keywords=ruby

(quite a surprising choice; I have heard 1.9 has never been encouraged and was kind of prototyped )

For the record, it works great with ruby 2.x

**Comment by bartavelle** [comment]
As you mentioned, this is a showstopper for the next release. However, this is most likely a `hruby` problem. I will try to solve it, but not in the short term. I might find time during the month.

**Comment by PierreR** [comment]
I believe we should jump up to 1.1 looking at the changelog and the recent serious bug that was fixed.

What do you think ?

**Comment by bartavelle** [comment]
That might be a good idea, yes. I'll try to do that during the week.

**Comment by bartavelle** [comment]
I uploaded the new version. I don't know what happened to the website, but it seems some posts were dropped. I'll try to find them, but I have a sinking feeling they are forever lost.

**Comment by PierreR** [comment]
You didn't wait for the hruby fix then ?

**Comment by bartavelle** [comment]
No I don't know when I'll be able to deliver it ... :(

**Comment by bartavelle** [comment]
So I just asked the person I know that is the most knowledgeable about ruby, and he pointed me to this :

https://github.com/DFHack/dfhack/issues/271#issuecomment-55113005

I don't know how to take control of the primary thread in Haskell, I'll dig a little bit.

**Comment by bartavelle** [comment]
Ok that doesn't look fixable at all, I'll have to prevent hruby from building with against 1.9 ...
