### ISSUE TITLE
NativeType File reject mode 'ug=rwx,o=r'

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#89]
`'ug=rwx,o=r'` is a valid mode for file resource that is reject by puppetresources with the error:

```
Invalid mode size at
```

**Comment by bartavelle** [comment]
What does that even  mean ? It makes sense for `chmod` because there already is a file, but what is it doing when a file is to be created ? Handle it like it was `000` ?

**Comment by PierreR** [comment]
Is it not the same as '0774' ?

**Comment by bartavelle** [comment]
Argh I did read `ug+rwx` ... In that case it is well defined.

**Comment by bartavelle** [comment]
Actually it doesn't mean `0774` because you shouldn't touch the `suid` bits ...

**Comment by bartavelle** [comment]
It's `?774`

**Comment by bartavelle** [comment]
How does that even work ? https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/file/posix.rb#L119-L135

**Comment by bartavelle** [comment]
I just pushed a quick fix. Is that ok for your use case ?

**Comment by PierreR** [comment]
I will test it tomorrow. Thanks.

This issue is not really personal this time ;-) I quickly change the `ug+rwx` to `774`. But as it might hurt adoption I believe the fix is welcomed.

**Comment by PierreR** [comment]
Work nicely except that it silently fails (set to 0) when using nonsensical input such as `ug=rwx,o=z` or `zg=rwx`

**Comment by bartavelle** [comment]
An untested quick fix is on its way !

**Comment by PierreR** [comment]
;-)

I have just noticed that `puppet-lint` actually forces a fix (by default) to use a 4 digit value:

```
FIXED: mode should be represented as a 4 digit octal value or symbolic mode on line 35
```

**Comment by PierreR** [comment]
I have done some more testing. Looks fine. Thanks.
