### ISSUE TITLE
Path for file resource source attribute is not checked anymore

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#90]
This was probably a nice test : 
https://github.com/bartavelle/language-puppet/blob/a7fa1dcff3fbfad6e7686311cde458e8eb656b96/Puppet/Testing.hs#L164

I have been bitten by such an error recently that shamelessly made it across the CI border. So it might be worth put the check back in the file NativeTypes.

**Comment by bartavelle** [comment]
This is a great test IMO, I added it because this was a mistake I consistently made ...

**Comment by PierreR** [comment]
If I want to add it back where could I put this kind of IO testing ? I guess I won't be able to sneak IO in ` Puppet.NativeTypes.File` ?

**Comment by bartavelle** [comment]
You can't, and I think you shouldn't (because it should be an optional test). Perhaps it should be in its own module ...

**Comment by PierreR** [comment]
I can make a module `Puppet.TestCatalog` with a function `testCatalog` that would gather extra IO testing such as this one ?

Should I call this `testCatalog` function in `Puppet.Daemon` or inside `Puppet.Interpreter` ?

As an extra question what about using the `InterpreterReader` directly in the function [`getCatalog`](https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter.hs#L59) ? That would reduce the huge list of params and arguably increase the readeability of the function.

**Comment by bartavelle** [comment]
All of this sound sensible to me.

**Comment by PierreR** [comment]
Why does it need to be an optional test ?

Otherwise I guess it could be checked in https://github.com/bartavelle/language-puppet/blob/master/Puppet/NativeTypes.hs#L50 if we add `fileExist` to the list of [`ImpureMethods`](https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter/Types.hs#L188) ?

**Comment by bartavelle** [comment]
You might not want to keep the files on your local system, or in the same
source control repository!

**Comment by PierreR** [comment]
Another nitpick.

Is it really useful to have [manifestPath, modulePath and templatePath] (https://github.com/bartavelle/language-puppet/blob/master/Puppet/Preferences.hs#L25-L27) in Preferences ? It cannot really be changed, can it ? On the other hand, I would find handy to keep the puppet base directory in there.

Also while trying to understand the code, I am changing the haddock of [getCalog](https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter.hs#L62) for the following:
```
{-| Call the operational 'interpretMonad' function to compute the catalog.
    Returns either an error, or a tuple containing all the resources,
    dependency map, exported resources, and defined resources alongside with
    all messages that have been generated by the compilation process.

    The later 'definedResources' (eg. all class declarations) are pulled out of the
    'InterpreterState' and might not be up to date. There are only useful for code coverage tests.
-}
```
Is this correct ? Are puppet defined resource types part of the 'definedResources' ? Do we really need to return these 'definedResources' from `getCatalog`. If I am correct, it is eventually use to find "deadcode" in PuppetResources. I don't know if it plays a critical role there.

**Comment by bartavelle** [comment]
Puppet lets you define arbitrary path for manifess, module and template, so that's why I wrote it like that. On the other hand, I don't think it is ever useful to separate them, so it might be a good idea to simplify things here.

I added all puppet defined resources in the returned catalog because it was useful for debugging (to me), but more importantly because it is used by the puppet client. I think this should not be removed !

**Comment by PierreR** [comment]
What do you mean by "used by the puppet client" ? I know the defined resources (which are the user defined resources, aren't they ?) are used by the Interpreter (to track deps for instance). It seems to be used by PuppetResources but just for finding 'deadcode' (don't know why it is so because this part of the code is still  a black box to me).

As for the paths, I still don't see how I can simplify things by bundling modules, file and template paths together ... If I make another data constructor for them, I will need lenses and end up with something that is arguably cleaner (but surely not simpler). Do you have another idea in mind ?

**Comment by bartavelle** [comment]
The (official) puppet client uses them to track dependencies, so that when you generate a JSON catalog it will know how to chain its actions.

I don't have a particular idea to clean those fields. There are already lensy if I am not mistaken, so it will not be more complex anyway.

**Comment by PierreR** [comment]
Could you review this last commit ?

PS: there is still the problem related to #20 that we can fix later on.
