### ISSUE TITLE
Is the StateWriter module really used ?

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#91]
I don't understand how the `stateWriter` module would be used instead of the regular `Writer/State` monad.

The only place where the `stateWriter` is imported is [here](
https://github.com/bartavelle/language-puppet/blob/eed3d6117e53a49f85c3a68c283fe8bdd6976c73/Puppet/Interpreter/IO.hs#L14-L15)

And it merely re-used the re-export of `Data.Monoid`.

I would expect the tell from [here]( 
https://github.com/bartavelle/language-puppet/blob/master/Puppet/Interpreter/Types.hs#L235) to have a `MonadWriter InterpreterWriter m` that comes from the `stateWriter` module.

It looks like this has been removed in 30222455a098d0. By mistake ?

**Comment by bartavelle** [comment]
I don't think it's used anymore, I'll try to build without it.

**Comment by bartavelle** [comment]
Just removed it.
