### ISSUE TITLE
Explicit export for Puppet.Interpreter.Types

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#92]
I am about to commit this change.

Let me know if this is OK by you.

**Comment by bartavelle** [comment]
Where can I see it ?

**Comment by PierreR** [comment]
Wait a minute ;-)

**Comment by PierreR** [comment]
Here is it :  606ebda57ac756045e04ee1cc08b52f92a41d70a

**Comment by bartavelle** [comment]
I hope it's full of my code so that I'll have stuff to bitch about.

**Comment by PierreR** [comment]
I would like to go from there and improve the haddock a bit.

**Comment by bartavelle** [comment]
Looks like a good idea to me. You will indeed be in a good position to fix the haddocks with explicit exports.

**Comment by PierreR** [comment]
Do you think it is a good idea to disable the access to direct attribute such as `_rnode` aka changing `import Resource(..)` into `import Resource(Resource)` ?

Then my lens skill feels short to fix this:
```
            res <- ( map (rvirtuality .~ Normal)
                   . filter ((/= fqdn) . _rnode)
                   ) <$> singleton (PDBGetResources q)
```
In `Interpreter.hs`

**Comment by bartavelle** [comment]
You can replace all accessor uses like `_rnode` by something like `view rnode`, if that is your problem.

You can have the left hand side of `<$>` be more "lensy", but I think it might just be obfuscated to others ...

**Comment by bartavelle** [comment]
```
            res <- toListOf ( folded
                            ∘ filtered ( hasn't (rnode ∘ only fqdn) )
                            ∘ to (rvirtuality .~ Normal)
                   ) <$> singleton (PDBGetResources q)
```

**Comment by bartavelle** [comment]
hum not sure it does what I am expecting

**Comment by bartavelle** [comment]
Actually it does :)
