### ISSUE TITLE
Stats are not showing up correctly (`-a` option)

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#93]
I have just realized that my 889563a867152f8d50ff275644b377b1ed9d6c97 commit has broken the statistic report in `PuppetResources.hs` (when using the `-a` option)

I will have a look but maybe you'll have an immediate piecing debug lense ;-)

**Comment by PierreR** [comment]
Wicked ! The order matters here ...

**Comment by bartavelle** [comment]
The joys of imperative code !
