### ISSUE TITLE
Missing curly brace in variable is not catched.

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#94]
Hello,

Even in strict mode, this kind of error is not catched:
```
  $halcyon_dir = "$halcyon_base}/halcyon"
```
Shouldn't it fail at parsing time already ?

Cheers,

**Comment by bartavelle** [comment]
Does puppet fails this ? I don't think it should fail, but who knows ...

**Comment by PierreR** [comment]
I don't know. Do you think it would resolve the variable all the same ? `puppetresources` doesn't that's for sure.

**Comment by bartavelle** [comment]
Given that `\}` isn't a valid escape, I would expect this :

```
$a = 'foo'
$b = "$a{"
```

to mean that `$b` is in fact `foo{`.

**Comment by PierreR** [comment]
You are right. That's what `puppetresources` is doing. I don't know why I believe it was not interpolate.

I will check that puppet is doing the same and close the issue if it fits.

**Comment by PierreR** [comment]
Confirm that it works as expected:
```
puppet apply -e '$a="toto" $b="$a}hello" notify {"$b":}'
Notice: toto}hello

```
