### ISSUE TITLE
Empty resource declarations are accepted

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#95]
An empty resource declaration (for package for instance) is accepted

```
  package {
  }
```
This will be refused by the puppet master with:
```
All resource specifications require names; expected '%s' at /
```

**Comment by bartavelle** [comment]
Should be fixed now !

**Comment by PierreR** [comment]
Work fine. Thanks.

It would suggest a new release. Though it might be nice to wait for #88 to be fixed.
