### ISSUE TITLE
In permissive mode, return undef when looking up an undef key

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#97]
I think it makes sense to follow `puppet` behavior in `permissive mode` as it is going to stick quite a while (if not ever).

Any PR I submit to `puppetlabs` modules to solve the problem looks rather `adhoc`. I am not  convinced that using `has_key` is so much better ;-) 

In fine, I am wondering if the current puppet behavior is not what people generally expect in dynamically typed languages (even in python the default value is `None` for the get function)

What do you think ?

**Comment by bartavelle** [comment]
I agree with you. I am fine with the permissive approach, as I can still use strict mode for my personal use.
